from components import (
    CHAT_INPUT_TEMPLATE,
    CHAT_OUTPUT_TEMPLATE,
    TEXT_INPUT_TEMPLATE,
    TEXT_OUTPUT_TEMPLATE,
    LANGUAGE_MODEL_TEMPLATE,
    OPENAI_MODEL_TEMPLATE,
    PROMPT_TEMPLATE,
    AGENT_TEMPLATE,
    CALCULATOR_TEMPLATE,
    WEB_SEARCH_TEMPLATE,
    MCP_TOOLS_TEMPLATE,
    MCP_NODE_TEMPLATE,
    QPIAI_MCP_TOOLS_TEMPLATE,
    QPIAI_MCP_NODE_TEMPLATE,
    IF_ELSE_TEMPLATE,
    TYPE_CONVERT_TEMPLATE,
    FILE_TEMPLATE
)

NEW_COMPONENT_TEMPLATES = {
    "OpenAIModel": OPENAI_MODEL_TEMPLATE,
    "Agent": AGENT_TEMPLATE,
    "ChatInput": CHAT_INPUT_TEMPLATE,
    "Prompt": PROMPT_TEMPLATE,
    "LanguageModel": LANGUAGE_MODEL_TEMPLATE,
    "ChatOutput": CHAT_OUTPUT_TEMPLATE,
    "Calculator": CALCULATOR_TEMPLATE,
    "WebSearch": WEB_SEARCH_TEMPLATE,
    "TextInput": TEXT_INPUT_TEMPLATE,
    "TextOutput": TEXT_OUTPUT_TEMPLATE,
    "MCPTools": MCP_TOOLS_TEMPLATE,
    "MCPNode": MCP_NODE_TEMPLATE,
    "QPIAITools": QPIAI_MCP_TOOLS_TEMPLATE,
    "QPIAINode": QPIAI_MCP_NODE_TEMPLATE,
    "If_Else": IF_ELSE_TEMPLATE,
    "Type_Convert": TYPE_CONVERT_TEMPLATE,
    "File": FILE_TEMPLATE
}