CHAT_INPUT_TEMPLATE = {
    "description": "Get chat inputs from the Playground.",
    "display_name": "Chat Input",
    "icon": "MessagesSquare",
    "base_classes": ["Message"],
    "beta": False,
    "conditional_paths": [],
    "custom_fields": {},
    "documentation": "",
    "edited": False,
    "frozen": False,
    "legacy": False,
    "lf_version": "1.4.3",
    "metadata": {},
    "output_types": [],
    "pinned": False,
    "outputs": [{
        "allows_loop": False,
        "cache": True,
        "display_name": "Chat Message",
        "group_outputs": False,
        "method": "message_response",
        "name": "message",
        "selected": "Message",
        "tool_mode": True,
        "types": ["Message"],
        "value": "__UNDEFINED__"
    }],
    "field_order": [
        "input_value",
        "should_store_message",
        "sender",
        "sender_name",
        "session_id",
        "files",
        "background_color",
        "chat_icon",
        "text_color"
    ],
    "template": {
        "_type": "Component",
        "background_color": {
            "_input_type": "MessageTextInput",
            "advanced": True,
            "display_name": "Background Color",
            "dynamic": False,
            "info": "The background color of the icon.",
            "input_types": ["Message"],
            "list": False,
            "list_add_label": "Add More",
            "load_from_db": False,
            "name": "background_color",
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "type": "str",
            "value": ""
        },
        "chat_icon": {
            "_input_type": "MessageTextInput",
            "advanced": True,
            "display_name": "Icon",
            "dynamic": False,
            "info": "The icon of the message.",
            "input_types": ["Message"],
            "list": False,
            "list_add_label": "Add More",
            "load_from_db": False,
            "name": "chat_icon",
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "type": "str",
            "value": ""
        },
        "input_value": {
            "_input_type": "MultilineInput",
            "advanced": False,
            "copy_field": False,
            "display_name": "Input Text",
            "dynamic": False,
            "info": "Message to be passed as input.",
            "input_types": [],
            "list": False,
            "list_add_label": "Add More",
            "load_from_db": False,
            "multiline": True,
            "name": "input_value",
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "type": "str",
            "value": ""
        },
        "sender": {
            "_input_type": "DropdownInput",
            "advanced": True,
            "combobox": False,
            "dialog_inputs": {},
            "display_name": "Sender Type",
            "dynamic": False,
            "info": "Type of sender.",
            "name": "sender",
            "options": ["Machine", "User"],
            "options_metadata": [],
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "toggle": False,
            "tool_mode": False,
            "trace_as_metadata": True,
            "type": "str",
            "value": "User"
        },
        "sender_name": {
            "_input_type": "MessageTextInput",
            "advanced": True,
            "display_name": "Sender Name",
            "dynamic": False,
            "info": "Name of the sender.",
            "input_types": ["Message"],
            "list": False,
            "list_add_label": "Add More",
            "load_from_db": False,
            "name": "sender_name",
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "type": "str",
            "value": "User"
        },
        "should_store_message": {
            "_input_type": "BoolInput",
            "advanced": True,
            "display_name": "Store Messages",
            "dynamic": False,
            "info": "Store the message in the history.",
            "list": False,
            "list_add_label": "Add More",
            "name": "should_store_message",
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "tool_mode": False,
            "trace_as_metadata": True,
            "type": "bool",
            "value": True
        },
        "session_id": {
            "_input_type": "MessageTextInput",
            "advanced": True,
            "display_name": "Session ID",
            "dynamic": False,
            "info": "The session ID of the chat. If empty, the current session ID parameter will be used.",
            "input_types": ["Message"],
            "list": False,
            "list_add_label": "Add More",
            "load_from_db": False,
            "name": "session_id",
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "type": "str",
            "value": ""
        },
        "files": {
            "_input_type": "FileInput",
            "advanced": True,
            "display_name": "Files",
            "dynamic": False,
            "fileTypes": [
                "txt", "md", "mdx", "csv", "json", "yaml", "yml", "xml", "html", "htm", 
                "pdf", "docx", "py", "sh", "sql", "js", "ts", "tsx", "jpg", "jpeg", 
                "png", "bmp", "image"
            ],
            "file_path": "",
            "info": "Files to be sent with the message.",
            "is_list": True,
            "list": True,
            "list_add_label": "Add More",
            "name": "files",
            "placeholder": "",
            "required": False,
            "show": True,
            "temp_file": True,
            "title_case": False,
            "trace_as_metadata": True,
            "type": "file",
            "value": ""
        },
        "text_color": {
            "_input_type": "MessageTextInput",
            "advanced": True,
            "display_name": "Text Color",
            "dynamic": False,
            "info": "The text color of the name",
            "input_types": ["Message"],
            "list": False,
            "list_add_label": "Add More",
            "load_from_db": False,
            "name": "text_color",
            "placeholder": "",
            "required": False,
            "show": True,
            "title_case": False,
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "type": "str",
            "value": ""
        },
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": "from langflow.base.data.utils import IMG_FILE_TYPES, TEXT_FILE_TYPES\nfrom langflow.base.io.chat import ChatComponent\nfrom langflow.inputs.inputs import BoolInput\nfrom langflow.io import (\n    DropdownInput,\n    FileInput,\n    MessageTextInput,\n    MultilineInput,\n    Output,\n)\nfrom langflow.schema.message import Message\nfrom langflow.utils.constants import (\n    MESSAGE_SENDER_AI,\n    MESSAGE_SENDER_NAME_USER,\n    MESSAGE_SENDER_USER,\n)\n\n\nclass ChatInput(ChatComponent):\n    display_name = \"Chat Input\"\n    description = \"Get chat inputs from the Playground.\"\n    icon = \"MessagesSquare\"\n    name = \"ChatInput\"\n    minimized = True\n\n    inputs = [\n        MultilineInput(\n            name=\"input_value\",\n            display_name=\"Input Text\",\n            value=\"\",\n            info=\"Message to be passed as input.\",\n            input_types=[],\n        ),\n        BoolInput(\n            name=\"should_store_message\",\n            display_name=\"Store Messages\",\n            info=\"Store the message in the history.\",\n            value=True,\n            advanced=True,\n        ),\n        DropdownInput(\n            name=\"sender\",\n            display_name=\"Sender Type\",\n            options=[MESSAGE_SENDER_AI, MESSAGE_SENDER_USER],\n            value=MESSAGE_SENDER_USER,\n            info=\"Type of sender.\",\n            advanced=True,\n        ),\n        MessageTextInput(\n            name=\"sender_name\",\n            display_name=\"Sender Name\",\n            info=\"Name of the sender.\",\n            value=MESSAGE_SENDER_NAME_USER,\n            advanced=True,\n        ),\n        MessageTextInput(\n            name=\"session_id\",\n            display_name=\"Session ID\",\n            info=\"The session ID of the chat. If empty, the current session ID parameter will be used.\",\n            advanced=True,\n        ),\n        FileInput(\n            name=\"files\",\n            display_name=\"Files\",\n            file_types=TEXT_FILE_TYPES + IMG_FILE_TYPES,\n            info=\"Files to be sent with the message.\",\n            advanced=True,\n            is_list=True,\n            temp_file=True,\n        ),\n        MessageTextInput(\n            name=\"background_color\",\n            display_name=\"Background Color\",\n            info=\"The background color of the icon.\",\n            advanced=True,\n        ),\n        MessageTextInput(\n            name=\"chat_icon\",\n            display_name=\"Icon\",\n            info=\"The icon of the message.\",\n            advanced=True,\n        ),\n        MessageTextInput(\n            name=\"text_color\",\n            display_name=\"Text Color\",\n            info=\"The text color of the name\",\n            advanced=True,\n        ),\n    ]\n    outputs = [\n        Output(display_name=\"Chat Message\", name=\"message\", method=\"message_response\"),\n    ]\n\n    async def message_response(self) -> Message:\n        background_color = self.background_color\n        text_color = self.text_color\n        icon = self.chat_icon\n\n        message = await Message.create(\n            text=self.input_value,\n            sender=self.sender,\n            sender_name=self.sender_name,\n            session_id=self.session_id,\n            files=self.files,\n            properties={\n                \"background_color\": background_color,\n                \"text_color\": text_color,\n                \"icon\": icon,\n            },\n        )\n        if self.session_id and isinstance(message, Message) and self.should_store_message:\n            stored_message = await self.send_message(\n                message,\n            )\n            self.message.value = stored_message\n            message = stored_message\n\n        self.status = message\n        return message\n"
        }
    },
    "tool_mode": False
}