FILE_TEMPLATE = {
    "display_name": "File",
    "description": "Loads content from one or more files as a DataFrame.",
    "icon": "file-text",
    "base_classes": [
        "DataFrame",
        "Message",
    ],
    "field_order": [
        "_type",
        "file_path",
        "path",
        "code",
        "concurrency_multithreading",
        "delete_server_file_after_processing",
        "ignore_unspecified_files",
        "ignore_unsupported_extensions",
        "separator",
        "silent_errors",
        "use_multithreading",
    ],
    "outputs": [
        {
            "types": ["DataFrame"],
            "selected": "DataFrame",
            "name": "dataframe",
            "display_name": "Loaded Files",
            "method": "load_files",
            "value": "__UNDEFINED__",
            "cache": True,
            "allows_loop": False,
            "group_outputs": False,
            "tool_mode": True,
        },
        {
            "types": ["Message"],
            "selected": "Message",
            "name": "message",
            "display_name": "Raw Content",
            "method": "load_files_message",
            "value": "__UNDEFINED__",
            "cache": True,
            "allows_loop": False,
            "group_outputs": False,
            "tool_mode": True,
        },
    ],
    "template": {
        "_type": "Component",
        "file_path": {
            "trace_as_metadata": True,
            "list": True,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "file_path",
            "value": "",
            "display_name": "Server File Path",
            "advanced": True,
            "input_types": [
                "Data",
                "Message",
            ],
            "dynamic": False,
            "info": "Data object with a 'file_path' property pointing to server file or a Message object with a path to the file. Supercedes 'Path' but supports same file types.",
            "title_case": False,
            "type": "other",
            "_input_type": "HandleInput",
        },
        "path": {
            "trace_as_metadata": True,
            "file_path": [],
            "fileTypes": [
                "txt",
                "md",
                "mdx",
                "csv",
                "json",
                "yaml",
                "yml",
                "xml",
                "html",
                "htm",
                "pdf",
                "docx",
                "py",
                "sh",
                "sql",
                "js",
                "ts",
                "tsx",
                "zip",
                "tar",
                "tgz",
                "bz2",
                "gz",
            ],
            "temp_file": False,
            "list": True,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "path",
            "value": [],
            "display_name": "Files",
            "advanced": False,
            "dynamic": False,
            "info": "Supported file extensions: txt, md, mdx, csv, json, yaml, yml, xml, html, htm, pdf, docx, py, sh, sql, js, ts, tsx; optionally bundled in file extensions: zip, tar, tgz, bz2, gz",
            "title_case": False,
            "type": "file",
            "_input_type": "FileInput",
        },
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": 'from langflow.base.data.base_file import BaseFileComponent\nfrom langflow.base.data.utils import TEXT_FILE_TYPES, parallel_load_data, parse_text_file_to_data\nfrom langflow.io import BoolInput, IntInput\nfrom langflow.schema.data import Data\n\n\nclass FileComponent(BaseFileComponent):\n    """Handles loading and processing of individual or zipped text files.\n\n    This component supports processing multiple valid files within a zip archive,\n    resolving paths, validating file types, and optionally using multithreading for processing.\n    """\n\n    display_name = "File"\n    description = "Loads content from one or more files as a DataFrame."\n    icon = "file-text"\n    name = "File"\n\n    VALID_EXTENSIONS = TEXT_FILE_TYPES\n\n    inputs = [\n        *BaseFileComponent._base_inputs,\n        BoolInput(\n            name="use_multithreading",\n            display_name="[Deprecated] Use Multithreading",\n            advanced=True,\n            value=True,\n            info="Set \'Processing Concurrency\' greater than 1 to enable multithreading.",\n        ),\n        IntInput(\n            name="concurrency_multithreading",\n            display_name="Processing Concurrency",\n            advanced=True,\n            info="When multiple files are being processed, the number of files to process concurrently.",\n            value=1,\n        ),\n    ]\n\n    outputs = [\n        *BaseFileComponent._base_outputs,\n    ]\n\n    def process_files(self, file_list: list[BaseFileComponent.BaseFile]) -> list[BaseFileComponent.BaseFile]:\n        """Processes files either sequentially or in parallel, depending on concurrency settings.\n\n        Args:\n            file_list (list[BaseFileComponent.BaseFile]): List of files to process.\n\n        Returns:\n            list[BaseFileComponent.BaseFile]: Updated list of files with merged data.\n        """\n\n        def process_file(file_path: str, *, silent_errors: bool = False) -> Data | None:\n            """Processes a single file and returns its Data object."""\n            try:\n                return parse_text_file_to_data(file_path, silent_errors=silent_errors)\n            except FileNotFoundError as e:\n                msg = f"File not found: {file_path}. Error: {e}"\n                self.log(msg)\n                if not silent_errors:\n                    raise\n                return None\n            except Exception as e:\n                msg = f"Unexpected error processing {file_path}: {e}"\n                self.log(msg)\n                if not silent_errors:\n                    raise\n                return None\n\n        if not file_list:\n            msg = "No files to process."\n            raise ValueError(msg)\n\n        concurrency = 1 if not self.use_multithreading else max(1, self.concurrency_multithreading)\n        file_count = len(file_list)\n\n        parallel_processing_threshold = 2\n        if concurrency < parallel_processing_threshold or file_count < parallel_processing_threshold:\n            if file_count > 1:\n                self.log(f"Processing {file_count} files sequentially.")\n            processed_data = [process_file(str(file.path), silent_errors=self.silent_errors) for file in file_list]\n        else:\n            self.log(f"Starting parallel processing of {file_count} files with concurrency: {concurrency}.")\n            file_paths = [str(file.path) for file in file_list]\n            processed_data = parallel_load_data(\n                file_paths,\n                silent_errors=self.silent_errors,\n                load_function=process_file,\n                max_concurrency=concurrency,\n            )\n\n        # Use rollup_basefile_data to merge processed data with BaseFile objects\n        return self.rollup_data(file_list, processed_data)\n'
        },
        "concurrency_multithreading": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "concurrency_multithreading",
            "value": 1,
            "display_name": "Processing Concurrency",
            "advanced": True,
            "dynamic": False,
            "info": "When multiple files are being processed, the number of files to process concurrently.",
            "title_case": False,
            "type": "int",
            "_input_type": "IntInput",
        },
        "delete_server_file_after_processing": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "delete_server_file_after_processing",
            "value": True,
            "display_name": "Delete Server File After Processing",
            "advanced": True,
            "dynamic": False,
            "info": "If true, the Server File Path will be deleted after processing.",
            "title_case": False,
            "type": "bool",
            "_input_type": "BoolInput",
        },
        "ignore_unspecified_files": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "ignore_unspecified_files",
            "value": False,
            "display_name": "Ignore Unspecified Files",
            "advanced": True,
            "dynamic": False,
            "info": "If true, Data with no 'file_path' property will be ignored.",
            "title_case": False,
            "type": "bool",
            "_input_type": "BoolInput",
        },
        "ignore_unsupported_extensions": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "ignore_unsupported_extensions",
            "value": True,
            "display_name": "Ignore Unsupported Extensions",
            "advanced": True,
            "dynamic": False,
            "info": "If true, files with unsupported extensions will not be processed.",
            "title_case": False,
            "type": "bool",
            "_input_type": "BoolInput",
        },
        "separator": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "separator",
            "value": "\n\n",
            "display_name": "Separator",
            "advanced": True,
            "dynamic": False,
            "info": "Specify the separator to use between multiple outputs in Message format.",
            "title_case": False,
            "type": "str",
            "_input_type": "StrInput",
        },
        "silent_errors": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "silent_errors",
            "value": False,
            "display_name": "Silent Errors",
            "advanced": True,
            "dynamic": False,
            "info": "If true, errors will not raise an exception.",
            "title_case": False,
            "type": "bool",
            "_input_type": "BoolInput",
        },
        "use_multithreading": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "use_multithreading",
            "value": True,
            "display_name": "[Deprecated] Use Multithreading",
            "advanced": True,
            "dynamic": False,
            "info": "Set 'Processing Concurrency' greater than 1 to enable multithreading.",
            "title_case": False,
            "type": "bool",
            "_input_type": "BoolInput",
        },
    },
}