MCP_TOOLS_TEMPLATE = {
    "display_name": "MCP Tools",
    "description": "Connect to MCP servers and expose selected tools for agent integration",
    "icon": "QpiAI",
    "base_classes": ["Tool"],
    "field_order": ["connection_type", "server_url", "headers", "timeout_seconds", "selected_tools"],
    "outputs": [
        {
            "types": ["Tool"],
            "selected": "Tool",
            "name": "component_as_tool",
            "display_name": "Tools",
            "method": "build_output",
            "value": "__UNDEFINED__",
            "cache": True,
            "required_inputs": None,
            "allows_loop": False,
            "group_outputs": False,
            "options": None,
            "tool_mode": True
        }
    ],
    "template": {
        "_type": "Component",
        "connection_type": {
            "_input_type": "DropdownInput",
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": ["http", "sse"],
            "options_metadata": [],
            "combobox": False,
            "dialog_inputs": {},
            "toggle": False,
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "connection_type",
            "value": "http",
            "display_name": "Connection Type",
            "advanced": False,
            "dynamic": False,
            "info": "",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str"
        },
        "server_url": {
            "_input_type": "MessageTextInput",
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "http://localhost:3001",
            "show": True,
            "name": "server_url",
            "value": "",
            "display_name": "HTTP Endpoint",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "HTTP endpoint for the MCP server",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str"
        },
        "headers": {
            "_input_type": "DictInput",
            "tool_mode": False,
            "trace_as_input": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": False,
            "name": "headers",
            "value": {},
            "display_name": "Headers",
            "advanced": True,
            "dynamic": False,
            "info": "",
            "title_case": False,
            "type": "dict"
        },
        "timeout_seconds": {
            "_input_type": "IntInput",
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "timeout_seconds",
            "value": 30,
            "display_name": "Timeout (seconds)",
            "advanced": True,
            "dynamic": False,
            "info": "",
            "title_case": False,
            "type": "int"
        },
        "selected_tools": {
            "_input_type": "DropdownInput",
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": ["all"],
            "options_metadata": [],
            "combobox": False,
            "dialog_inputs": {},
            "toggle": False,
            "required": False,
            "placeholder": "",
            "show": False,
            "name": "selected_tools",
            "value": "all",
            "display_name": "Selected Tools",
            "advanced": False,
            "dynamic": False,
            "info": "",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str"
        },
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": "import json\nimport re\nfrom typing import Any, Dict, List, Optional, Union\nimport asyncio\nfrom contextlib import AsyncExitStack\n\nimport httpx\nfrom mcp import ClientSession\nfrom mcp.client.sse import sse_client\n\nfrom langflow.custom.custom_component.component import Component\nfrom langflow.base.mcp.util import create_tool_coroutine, create_tool_func, create_input_schema_from_json_schema\nfrom langflow.io import (\n    DropdownInput,\n    IntInput,\n    MessageTextInput,\n    Output,\n    DictInput,\n)\nfrom langflow.logging import logger\nfrom langflow.schema.data import Data\nfrom langflow.schema.message import Message\n\n# Import required for tools\nfrom langchain_core.tools import StructuredTool\nfrom langflow.field_typing import Tool\n\n\ndef maybe_unflatten_dict(flat: Dict[str, Any]) -> Dict[str, Any]:\n    \"\"\"Convert flat dictionary with dot notation keys to nested structure.\"\"\"\n    if not any(re.search(r\"\\.|\\[\\d+\\]\", key) for key in flat):\n        return flat\n    nested: Dict[str, Any] = {}\n    array_re = re.compile(r\"^(.+)\\[(\\d+)\\]$\")\n    for key, val in flat.items():\n        parts = key.split(\".\")\n        cur = nested\n        for i, part in enumerate(parts):\n            m = array_re.match(part)\n            if m:\n                name, idx = m.group(1), int(m.group(2))\n                lst = cur.setdefault(name, [])\n                while len(lst) <= idx:\n                    lst.append({})\n                if i == len(parts) - 1:\n                    lst[idx] = val\n                else:\n                    cur = lst[idx]\n            elif i == len(parts) - 1:\n                cur[part] = val\n            else:\n                cur = cur.setdefault(part, {})\n    return nested\n\n\nclass MCPNodeClient:\n    \"\"\"MCP Client supporting SSE and HTTP connections.\"\"\"\n\n    def __init__(self):\n        self.session: Optional[ClientSession] = None\n        self.exit_stack = AsyncExitStack()\n        self.tools: List[Any] = []\n        self.server_url: Optional[str] = None\n        self.http_headers: Dict[str, str] = {}\n        self.http_client: Optional[httpx.AsyncClient] = None\n\n    def _parse_response(self, response: httpx.Response) -> dict:\n        \"\"\"Parse response handling both JSON and SSE formats.\"\"\"\n        content_type = response.headers.get(\"content-type\", \"\")\n\n        if \"text/event-stream\" in content_type:\n            # Handle SSE response\n            text = response.text.strip()\n            if not text:\n                return {}\n\n            # Parse SSE format: \"event: message\\ndata: {json}\\n\"\n            lines = text.split('\\n')\n            for line in lines:\n                if line.startswith('data: '):\n                    try:\n                        return json.loads(line[6:])  # Remove \"data: \" prefix\n                    except json.JSONDecodeError:\n                        continue\n            return {}\n        else:\n            # Handle JSON response\n            try:\n                return response.json()\n            except json.JSONDecodeError:\n                return {}\n\n    async def connect_http(self, url: str, headers: Optional[Dict[str, str]] = None,\n                          timeout_seconds: int = 30) -> List[Any]:\n        \"\"\"Connect to MCP server via HTTP transport (handles both JSON and SSE responses).\"\"\"\n        if headers is None:\n            headers = {}\n\n        try:\n            logger.info(f\"=== MCP HTTP Connection Attempt ===\")\n            logger.info(f\"URL: {url}\")\n            logger.info(f\"Additional headers: {headers}\")\n\n            # MCP HTTP transport headers as per specification\n            request_headers = {\n                **headers,\n                \"Content-Type\": \"application/json\",\n                \"Accept\": \"application/json, text/event-stream\",\n                \"MCP-Protocol-Version\": \"2025-03-26\"\n            }\n            logger.info(f\"Request headers: {request_headers}\")\n\n            # Create persistent HTTP client\n            self.http_client = httpx.AsyncClient(timeout=timeout_seconds)\n            self.server_url = url\n            self.http_headers = request_headers\n\n            # Step 1: Initialize connection\n            initialize_request = {\n                \"jsonrpc\": \"2.0\",\n                \"id\": \"init-1\",\n                \"method\": \"initialize\",\n                \"params\": {\n                    \"protocolVersion\": \"2025-03-26\",\n                    \"capabilities\": {},\n                    \"clientInfo\": {\n                        \"name\": \"langflow-mcp-node\",\n                        \"version\": \"1.0.0\"\n                    }\n                }\n            }\n\n            logger.info(f\"Sending initialize request to {url}\")\n            init_response = await self.http_client.post(url, json=initialize_request, headers=request_headers)\n            init_response.raise_for_status()\n\n            # Handle both JSON and SSE responses\n            init_result = self._parse_response(init_response)\n            logger.info(f\"Initialize response: {init_result}\")\n\n            if \"error\" in init_result:\n                raise ValueError(f\"Initialization failed: {init_result['error']}\")\n\n            # Extract session ID if provided\n            session_id = init_response.headers.get(\"Mcp-Session-Id\")\n            if session_id:\n                logger.info(f\"Got session ID: {session_id}\")\n                self.http_headers[\"Mcp-Session-Id\"] = session_id\n\n            # Step 2: List tools\n            list_tools_request = {\n                \"jsonrpc\": \"2.0\",\n                \"id\": \"tools-list-1\",\n                \"method\": \"tools/list\",\n                \"params\": {}\n            }\n\n            logger.info(\"Sending tools/list request\")\n            tools_response = await self.http_client.post(url, json=list_tools_request, headers=self.http_headers)\n            tools_response.raise_for_status()\n\n            # Handle both JSON and SSE responses\n            tools_data = self._parse_response(tools_response)\n            logger.info(f\"Tools response: {tools_data}\")\n\n            # Process tools response\n            if \"result\" in tools_data and \"tools\" in tools_data[\"result\"]:\n                tools = []\n                for tool_data in tools_data[\"result\"][\"tools\"]:\n                    tool_obj = type('Tool', (), {\n                        'name': tool_data.get('name'),\n                        'description': tool_data.get('description', ''),\n                        'inputSchema': tool_data.get('inputSchema', {})\n                    })()\n                    tools.append(tool_obj)\n\n                self.tools = tools\n                logger.info(f\"Successfully retrieved {len(tools)} tools\")\n                return tools\n            elif \"error\" in tools_data:\n                raise ValueError(f\"Tools list failed: {tools_data['error']}\")\n            else:\n                logger.warning(\"No tools found in response\")\n                return []\n\n        except httpx.HTTPStatusError as e:\n            error_text = e.response.text if hasattr(e.response, 'text') else str(e)\n            logger.error(f\"HTTP {e.response.status_code}: {error_text}\")\n\n            # If we get 500 with \"Server got itself in trouble\", try different URLs\n            if e.response.status_code == 500 and \"trouble\" in error_text:\n                # Try without /http/ suffix\n                if url.endswith('/http/'):\n                    logger.info(\"Trying without /http/ suffix...\")\n                    return await self.connect_http(url[:-6], headers, timeout_seconds)\n                # Try with different suffix\n                elif not url.endswith('/'):\n                    logger.info(\"Trying with trailing slash...\")\n                    return await self.connect_http(url + '/', headers, timeout_seconds)\n\n            raise ValueError(f\"HTTP {e.response.status_code}: {error_text}\")\n        except httpx.RequestError as e:\n            logger.error(f\"Request failed: {e}\")\n            raise ValueError(f\"Connection failed: {e}\")\n        except Exception as e:\n            logger.error(f\"HTTP connection failed: {e}\")\n            raise ValueError(f\"Connection failed: {e}\")\n\n    async def connect_sse(self, url: str, headers: Optional[Dict[str, str]] = None,\n                          timeout_seconds: int = 30) -> List[Any]:\n        if headers is None:\n            headers = {}\n        async with asyncio.timeout(timeout_seconds):\n            sse_transport = await self.exit_stack.enter_async_context(\n                sse_client(url, headers, timeout_seconds, timeout_seconds)\n            )\n            sse, write = sse_transport\n            self.session = await self.exit_stack.enter_async_context(ClientSession(sse, write))\n            await self.session.initialize()\n            resp = await self.session.list_tools()\n            self.tools = resp.tools\n            return self.tools\n\n    async def call_tool(self, tool_name: str, arguments: Dict[str, Any]) -> Any:\n        if self.session:\n            return await self.session.call_tool(tool_name, arguments=arguments)\n        elif self.http_client:\n            import uuid\n            req = {\"jsonrpc\": \"2.0\", \"id\": f\"tool-call-{uuid.uuid4().hex[:8]}\", \"method\": \"tools/call\", \"params\": {\"name\": tool_name, \"arguments\": arguments}}\n            resp = await self.http_client.post(self.server_url, json=req, headers=self.http_headers)\n            resp.raise_for_status()\n            result_data = resp.json().get(\"result\", {})\n            result = type(\"CallResult\", (), {\"content\": []})()\n            if \"content\" in result_data:\n                for item in result_data[\"content\"]:\n                    result.content.append(type(\"Content\", (), {\"text\": item.get(\"text\", str(item))})())\n            else:\n                result.content.append(type(\"Content\", (), {\"text\": str(result_data)})())\n            return result\n        else:\n            raise ValueError(\"Not connected to MCP server\")\n\n    async def run_tool(self, tool_name: str, arguments: dict):\n        \"\"\"Run a tool with the given arguments - this is what the utility functions expect\"\"\"\n        return await self.call_tool(tool_name, arguments)\n\n\nclass MCPToolComponent(Component):\n    display_name = \"MCP Tools\"\n    description = \"Connect to MCP servers and expose selected tools for agent integration\"\n    icon = \"QpiAI\"\n    name = \"MCPTools\" \n\n    client = MCPNodeClient()\n    tools: list = []\n    _tool_cache: dict = {}\n    default_keys: list[str] = [\n        \"code\", \"_type\", \"connection_type\", \"server_url\", \"headers\", \"timeout_seconds\", \"selected_tools\"\n    ]\n\n    inputs = [\n        DropdownInput(name=\"connection_type\", display_name=\"Connection Type\", options=[\"http\", \"sse\"], value=\"http\", real_time_refresh=True),\n        MessageTextInput(name=\"server_url\", display_name=\"HTTP Endpoint\", placeholder=\"http://localhost:3001\", info=\"HTTP endpoint for the MCP server\", show=True, real_time_refresh=True),\n        DictInput(name=\"headers\", display_name=\"Headers\", value={}, show=False, advanced=True),\n        IntInput(name=\"timeout_seconds\", display_name=\"Timeout (seconds)\", value=30, advanced=True),\n        DropdownInput(name=\"selected_tools\", display_name=\"Selected Tools\", options=[\"all\"], value=\"all\", show=False, real_time_refresh=True)\n    ]\n\n    outputs = [Output(display_name=\"Tools\", name=\"tools\", method=\"build_output\")]\n\n    async def update_tool_list(self):\n        try:\n            if self.connection_type == \"http\":\n                self.tools = await self.client.connect_http(self.server_url, getattr(self, \"headers\", {}), getattr(self, \"timeout_seconds\", 30))\n            elif self.connection_type == \"sse\":\n                self.tools = await self.client.connect_sse(self.server_url, getattr(self, \"headers\", {}), getattr(self, \"timeout_seconds\", 30))\n            self._tool_cache = {tool.name: tool for tool in self.tools if hasattr(tool, \"name\")}\n            return self.tools\n        except Exception as e:\n            logger.error(f\"Failed to update tools: {e}\")\n            self.tools = []\n            self._tool_cache = {}\n            return []\n\n    async def update_build_config(self, build_config: dict, field_value: Any, field_name: str | None = None) -> dict:\n        try:\n            if field_name == \"connection_type\":\n                # Show appropriate URL field based on connection type\n                if field_value == \"http\":\n                    build_config[\"server_url\"][\"display_name\"] = \"HTTP Endpoint\"\n                    build_config[\"server_url\"][\"placeholder\"] = \"http://localhost:3001\"\n                    build_config[\"server_url\"][\"info\"] = \"HTTP endpoint for the MCP server\"\n                elif field_value == \"sse\":\n                    build_config[\"server_url\"][\"display_name\"] = \"SSE Server URL\"\n                    build_config[\"server_url\"][\"placeholder\"] = \"http://localhost:3001/sse\"\n                    build_config[\"server_url\"][\"info\"] = \"SSE URL for the MCP server\"\n\n                build_config[\"server_url\"][\"show\"] = True\n                build_config[\"selected_tools\"][\"show\"] = False\n                build_config[\"selected_tools\"][\"options\"] = [\"all\"]\n                build_config[\"selected_tools\"][\"value\"] = \"all\"\n\n            elif field_name == \"server_url\" and field_value and field_value.strip():\n                # Basic URL validation\n                if not (field_value.startswith('http://') or field_value.startswith('https://')):\n                    build_config[\"selected_tools\"][\"options\"] = [\"all\", \"❌ Invalid URL\"]\n                    build_config[\"selected_tools\"][\"value\"] = \"❌ Invalid URL\"\n                    build_config[\"selected_tools\"][\"show\"] = True\n                    return build_config\n\n                try:\n                    tools = await self.update_tool_list()\n                    tool_names = [t.name for t in tools if hasattr(t, \"name\")]\n\n                    # Add \"all\" option plus individual tools\n                    build_config[\"selected_tools\"][\"options\"] = [\"all\"] + tool_names\n                    build_config[\"selected_tools\"][\"show\"] = len(tool_names) > 0\n                    build_config[\"selected_tools\"][\"value\"] = \"all\"\n\n                except Exception as e:\n                    logger.error(f\"Failed to update tool list: {e}\")\n                    build_config[\"selected_tools\"][\"show\"] = True\n                    build_config[\"selected_tools\"][\"options\"] = [\"all\", \"❌ Connection Failed\"]\n                    build_config[\"selected_tools\"][\"value\"] = \"❌ Connection Failed\"\n\n        except Exception as e:\n            logger.error(f\"Error updating build config: {e}\")\n        return build_config\n\n    async def build_output(self) -> list[Tool]:\n        \"\"\"Build tools with SSE-optimized connection\"\"\"\n\n        async def _build_with_sse_optimization():\n            try:\n                selected_tools = getattr(self, 'selected_tools', 'all')\n                server_url = getattr(self, 'server_url', '')\n                connection_type = getattr(self, 'connection_type', 'http')\n\n                logger.info(f\"Building MCP tools from {server_url} via {connection_type}\")\n                logger.info(f\"Selected tools: {selected_tools}\")\n\n                if selected_tools in [\"❌ Connection Failed\", \"❌ Invalid URL\"]:\n                    raise ValueError(\"Connection failed - check server URL\")\n\n                if not server_url or not server_url.strip():\n                    raise ValueError(\"No server URL provided\")\n\n                # Use cached tools if available, otherwise connect\n                if not self.tools:\n                    self.tools = await self.update_tool_list()\n\n                if not self.tools:\n                    raise ValueError(\"No tools returned from server\")\n\n                # Filter tools based on selection\n                if selected_tools == \"all\" or not selected_tools:\n                    filtered_tools = self.tools\n                else:\n                    # Handle single tool selection\n                    filtered_tools = []\n                    for tool in self.tools:\n                        if hasattr(tool, 'name') and tool.name == selected_tools:\n                            filtered_tools.append(tool)\n\n                if not filtered_tools:\n                    raise ValueError(f\"No tools found for selection: {selected_tools}\")\n\n                # Create Langflow tools\n                tool_list = []\n                for mcp_tool in filtered_tools:\n                    if hasattr(mcp_tool, 'name'):\n                        try:\n                            args_schema = create_input_schema_from_json_schema(\n                                getattr(mcp_tool, 'inputSchema', {})\n                            )\n\n                            langflow_tool = StructuredTool(\n                                name=mcp_tool.name,\n                                description=getattr(mcp_tool, 'description', ''),\n                                coroutine=create_tool_coroutine(mcp_tool.name, args_schema, self.client),\n                                func=create_tool_func(mcp_tool.name, args_schema, self.client),\n                                args_schema=args_schema,\n                                handle_tool_error=True\n                            )\n                            tool_list.append(langflow_tool)\n                            logger.debug(f\"Created tool: {mcp_tool.name}\")\n\n                        except Exception as e:\n                            logger.error(f\"Failed to create tool {mcp_tool.name}: {e}\")\n                            continue\n\n                if not tool_list:\n                    raise ValueError(\"No tools were successfully created\")\n\n                tool_names = [tool.name for tool in filtered_tools]\n                logger.info(f\"Successfully created {len(tool_list)} tools: {tool_names}\")\n                return tool_list\n\n            except Exception as e:\n                logger.error(f\"SSE-optimized build failed: {e}\")\n                raise ValueError(f\"Build failed: {str(e)}\")\n\n        # Shield the build process with generous timeout for SSE issues\n        try:\n            return await asyncio.wait_for(\n                asyncio.shield(_build_with_sse_optimization()),\n                timeout=90  # Allow time for SSE retries (3 attempts × 35s max + buffer)\n            )\n        except asyncio.TimeoutError:\n            error_msg = \"Build timed out after 90s - SSE connection issues persist\"\n            logger.error(error_msg)\n            raise ValueError(error_msg)\n        except asyncio.CancelledError:\n            error_msg = \"Build cancelled by Langflow\"\n            logger.warning(error_msg)\n            raise ValueError(error_msg)\n        except Exception as e:\n            error_msg = f\"Build failed: {str(e)}\"\n            logger.error(error_msg)\n            raise ValueError(error_msg)\n\n    async def cleanup(self):\n        \"\"\"Cleanup for Langflow\"\"\"\n        try:\n            await self.client.exit_stack.aclose()\n        except Exception as e:\n            logger.debug(f\"Cleanup error: {e}\")"
        }
    }
}