MCP_NODE_TEMPLATE =     {
    "display_name": "MCP Node",
    "description": "Connect to MCP servers and use their tools directly as workflow nodes",
    "icon": "QpiAI",
    "base_classes": [
        "Data",
        "Message",
    ],
    "field_order": [
        "_type",
        "code",
        "connection_type",
        "headers",
        "output_format",
        "server_url",
        "stdio_args",
        "stdio_command",
        "timeout_seconds",
        "tool_name",
    ],
    "outputs": [
        {
            "types": [
                "Data",
                "Message",
            ],
            "selected": "Data",
            "name": "result",
            "hidden": None,
            "display_name": "Result",
            "method": "build_output",
            "value": "__UNDEFINED__",
            "cache": True,
            "required_inputs": None,
            "allows_loop": False,
            "group_outputs": False,
            "options": None,
            "tool_mode": True,
        },
    ],
    "template": {
        "_type": "Component",
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": 'import json\nimport re\nfrom typing import Any, Dict, List, Optional, Union\nimport asyncio\nfrom contextlib import AsyncExitStack\n\nimport httpx\nfrom mcp import ClientSession, types\nfrom mcp.client.sse import sse_client\nfrom mcp.client.stdio import stdio_client\n\nfrom langflow.custom.custom_component.component import Component\nfrom langflow.io import (\n    BoolInput,\n    DropdownInput,\n    IntInput,\n    MessageTextInput,\n    MultilineInput,\n    Output,\n    StrInput,\n    DictInput,\n    FloatInput\n)\nfrom langflow.logging import logger\nfrom langflow.schema.data import Data\nfrom langflow.schema.message import Message\n\n\ndef maybe_unflatten_dict(flat: Dict[str, Any]) -> Dict[str, Any]:\n    """Convert flat dictionary with dot notation keys to nested structure."""\n    if not any(re.search(r"\\.|\\[\\d+\\]", key) for key in flat):\n        return flat\n\n    nested: Dict[str, Any] = {}\n    array_re = re.compile(r"^(.+)\\[(\\d+)\\]$")\n\n    for key, val in flat.items():\n        parts = key.split(".")\n        cur = nested\n        for i, part in enumerate(parts):\n            m = array_re.match(part)\n            if m:\n                name, idx = m.group(1), int(m.group(2))\n                lst = cur.setdefault(name, [])\n                while len(lst) <= idx:\n                    lst.append({})\n                if i == len(parts) - 1:\n                    lst[idx] = val\n                else:\n                    cur = lst[idx]\n            elif i == len(parts) - 1:\n                cur[part] = val\n            else:\n                cur = cur.setdefault(part, {})\n\n    return nested\n\n\nclass MCPNodeClient:\n    """MCP Client for both SSE and stdio connections."""\n\n    def __init__(self):\n        self.session: Optional[ClientSession] = None\n        self.exit_stack = AsyncExitStack()\n        self.tools: List[Any] = []\n        self.server_url: Optional[str] = None\n        self.session_id: Optional[str] = None\n        self.http_headers: Dict[str, str] = {}\n        self.http_client: Optional[httpx.AsyncClient] = None\n\n    def _parse_response(self, response: httpx.Response) -> dict:\n        """Parse response handling both JSON and SSE formats."""\n        content_type = response.headers.get("content-type", "")\n\n        if "text/event-stream" in content_type:\n            # Handle SSE response\n            text = response.text.strip()\n            if not text:\n                return {}\n\n            # Parse SSE format: "event: message\\ndata: {json}\\n"\n            lines = text.split(\'\\n\')\n            for line in lines:\n                if line.startswith(\'data: \'):\n                    try:\n                        return json.loads(line[6:])  # Remove "data: " prefix\n                    except json.JSONDecodeError:\n                        continue\n            return {}\n        else:\n            # Handle JSON response\n            try:\n                return response.json()\n            except json.JSONDecodeError:\n                return {}\n\n    async def connect_http(self, url: str, headers: Optional[Dict[str, str]] = None,\n                          timeout_seconds: int = 30) -> List[Any]:\n        """Connect to MCP server via HTTP transport (handles both JSON and SSE responses)."""\n        if headers is None:\n            headers = {}\n\n        try:\n            logger.info(f"=== MCP HTTP Connection Attempt ===")\n            logger.info(f"URL: {url}")\n            logger.info(f"Additional headers: {headers}")\n\n            # MCP HTTP transport headers as per specification\n            request_headers = {\n                **headers,\n                "Content-Type": "application/json",\n                "Accept": "application/json, text/event-stream",\n                "MCP-Protocol-Version": "2025-03-26"\n            }\n            logger.info(f"Request headers: {request_headers}")\n\n            # Create persistent HTTP client\n            self.http_client = httpx.AsyncClient(timeout=timeout_seconds)\n            self.server_url = url\n            self.http_headers = request_headers\n\n            # Step 1: Initialize connection\n            initialize_request = {\n                "jsonrpc": "2.0",\n                "id": "init-1",\n                "method": "initialize",\n                "params": {\n                    "protocolVersion": "2025-03-26",\n                    "capabilities": {},\n                    "clientInfo": {\n                        "name": "langflow-mcp-node",\n                        "version": "1.0.0"\n                    }\n                }\n            }\n\n            logger.info(f"Sending initialize request to {url}")\n            init_response = await self.http_client.post(url, json=initialize_request, headers=request_headers)\n            init_response.raise_for_status()\n\n            # Handle both JSON and SSE responses\n            init_result = self._parse_response(init_response)\n            logger.info(f"Initialize response: {init_result}")\n\n            if "error" in init_result:\n                raise ValueError(f"Initialization failed: {init_result[\'error\']}")\n\n            # Extract session ID if provided\n            session_id = init_response.headers.get("Mcp-Session-Id")\n            if session_id:\n                logger.info(f"Got session ID: {session_id}")\n                self.http_headers["Mcp-Session-Id"] = session_id\n                self.session_id = session_id\n\n            # Step 2: List tools\n            list_tools_request = {\n                "jsonrpc": "2.0",\n                "id": "tools-list-1",\n                "method": "tools/list",\n                "params": {}\n            }\n\n            logger.info("Sending tools/list request")\n            tools_response = await self.http_client.post(url, json=list_tools_request, headers=self.http_headers)\n            tools_response.raise_for_status()\n\n            # Handle both JSON and SSE responses\n            tools_data = self._parse_response(tools_response)\n            logger.info(f"Tools response: {tools_data}")\n\n            # Process tools response\n            if "result" in tools_data and "tools" in tools_data["result"]:\n                tools = []\n                for tool_data in tools_data["result"]["tools"]:\n                    tool_obj = type(\'Tool\', (), {\n                        \'name\': tool_data.get(\'name\'),\n                        \'description\': tool_data.get(\'description\', \'\'),\n                        \'inputSchema\': tool_data.get(\'inputSchema\', {})\n                    })()\n                    tools.append(tool_obj)\n\n                self.tools = tools\n                logger.info(f"Successfully retrieved {len(tools)} tools")\n                return tools\n            elif "error" in tools_data:\n                raise ValueError(f"Tools list failed: {tools_data[\'error\']}")\n            else:\n                logger.warning("No tools found in response")\n                return []\n\n        except httpx.HTTPStatusError as e:\n            error_text = e.response.text if hasattr(e.response, \'text\') else str(e)\n            logger.error(f"HTTP {e.response.status_code}: {error_text}")\n\n            # If we get 500 with "Server got itself in trouble", try different URLs\n            if e.response.status_code == 500 and "trouble" in error_text:\n                # Try without /http/ suffix\n                if url.endswith(\'/http/\'):\n                    logger.info("Trying without /http/ suffix...")\n                    return await self.connect_http(url[:-6], headers, timeout_seconds)\n                # Try with different suffix\n                elif not url.endswith(\'/\'):\n                    logger.info("Trying with trailing slash...")\n                    return await self.connect_http(url + \'/\', headers, timeout_seconds)\n\n            raise ValueError(f"HTTP {e.response.status_code}: {error_text}")\n        except httpx.RequestError as e:\n            logger.error(f"Request failed: {e}")\n            raise ValueError(f"Connection failed: {e}")\n        except Exception as e:\n            logger.error(f"HTTP connection failed: {e}")\n            raise ValueError(f"Connection failed: {e}")\n\n    async def connect_sse(self, url: str, headers: Optional[Dict[str, str]] = None,\n                         timeout_seconds: int = 30) -> List[Any]:\n        """Connect to MCP server via SSE."""\n        if headers is None:\n            headers = {}\n\n        try:\n            # Check for redirects\n            async with httpx.AsyncClient(follow_redirects=False) as client:\n                response = await client.request("HEAD", url)\n                if response.status_code == 307:\n                    url = response.headers.get("Location", url)\n\n            async with asyncio.timeout(timeout_seconds):\n                sse_transport = await self.exit_stack.enter_async_context(\n                    sse_client(url, headers, timeout_seconds, timeout_seconds)\n                )\n                sse, write = sse_transport\n                self.session = await self.exit_stack.enter_async_context(\n                    ClientSession(sse, write)\n                )\n                await self.session.initialize()\n                response = await self.session.list_tools()\n                self.tools = response.tools\n                return self.tools\n\n        except Exception as e:\n            logger.error(f"Failed to connect via SSE: {e}")\n            raise\n\n    async def connect_stdio(self, command: str, args: Optional[List[str]] = None,\n                           timeout_seconds: int = 30) -> List[Any]:\n        """Connect to MCP server via stdio."""\n        if args is None:\n            args = []\n\n        try:\n            async with asyncio.timeout(timeout_seconds):\n                stdio_transport = await self.exit_stack.enter_async_context(\n                    stdio_client(command, args)\n                )\n                stdio_read, stdio_write = stdio_transport\n                self.session = await self.exit_stack.enter_async_context(\n                    ClientSession(stdio_read, stdio_write)\n                )\n                await self.session.initialize()\n                response = await self.session.list_tools()\n                self.tools = response.tools\n                return self.tools\n\n        except Exception as e:\n            logger.error(f"Failed to connect via stdio: {e}")\n            raise\n\n    async def call_tool(self, tool_name: str, arguments: Dict[str, Any]) -> Any:\n        """Call a specific tool with arguments."""\n        try:\n            # Check if we have a session (SSE) or HTTP client (Streamable HTTP)\n            if self.session:\n                # Use session for SSE connections\n                result = await self.session.call_tool(tool_name, arguments=arguments)\n                return result\n            elif hasattr(self, \'http_client\') and self.http_client:\n                # Use HTTP client for HTTP connections\n                import uuid\n                call_request = {\n                    "jsonrpc": "2.0",\n                    "id": f"tool-call-{uuid.uuid4().hex[:8]}",\n                    "method": "tools/call",\n                    "params": {\n                        "name": tool_name,\n                        "arguments": arguments\n                    }\n                }\n\n                response = await self.http_client.post(self.server_url, json=call_request, headers=self.http_headers)\n                response.raise_for_status()\n                result_data = self._parse_response(response)\n\n                if "error" in result_data:\n                    raise ValueError(f"Tool call failed: {result_data[\'error\']}")\n\n                # Create a mock result object that matches MCP client expectations\n                result = type(\'CallResult\', (), {\n                    \'content\': []\n                })()\n\n                if "result" in result_data:\n                    # Handle different result formats\n                    result_content = result_data["result"]\n                    if isinstance(result_content, dict) and "content" in result_content:\n                        # Standard MCP response format\n                        content_items = result_content["content"]\n                        for item in content_items:\n                            content_obj = type(\'Content\', (), {\n                                \'text\': item.get(\'text\', str(item))\n                            })()\n                            result.content.append(content_obj)\n                    else:\n                        # Simple response format\n                        content_obj = type(\'Content\', (), {\n                            \'text\': str(result_content)\n                        })()\n                        result.content.append(content_obj)\n\n                return result\n            else:\n                raise ValueError("Not connected to MCP server")\n\n        except Exception as e:\n            logger.error(f"Tool \'{tool_name}\' execution failed: {e}")\n            raise\n\n\nclass MCPNodeComponent(Component):\n    """MCP Node Component - Use MCP server tools directly as nodes without agents."""\n\n    display_name = "MCP Node"\n    description = "Connect to MCP servers and use their tools directly as workflow nodes"\n    icon = "QpiAI"\n    name = "MCPNode"\n\n    # Use exact same pattern as MCPToolsComponent\n    schema_inputs: list = []\n    client = MCPNodeClient()\n    tools: list = []\n    _tool_cache: dict = {}\n    default_keys: list[str] = [\n        "code",\n        "_type",\n        "connection_type",\n        "server_url",\n        "stdio_command",\n        "stdio_args",\n        "headers",\n        "timeout_seconds",\n        "tool_name",\n        "output_format"\n    ]\n\n    inputs = [\n        DropdownInput(\n            name="connection_type",\n            display_name="Connection Type",\n            options=["http", "sse"],\n            value="http",\n            info="MCP transport type (http: Standard HTTP JSON-RPC, sse: Server-Sent Events)",\n            real_time_refresh=True\n        ),\n        MessageTextInput(\n            name="server_url",\n            display_name="Server URL",\n            info="MCP server URL (paste your full URL here)",\n            placeholder="https://your-server.com/mcp",\n            show=True,\n            real_time_refresh=True\n        ),\n        MessageTextInput(\n            name="stdio_command",\n            display_name="Command",\n            info="Command to run for stdio connection (e.g., \'python\', \'node\')",\n            placeholder="python",\n            show=False,\n            real_time_refresh=True\n        ),\n        MessageTextInput(\n            name="stdio_args",\n            display_name="Arguments",\n            info="Command arguments separated by spaces",\n            placeholder="server.py",\n            show=False,\n            advanced=True\n        ),\n        DictInput(\n            name="headers",\n            display_name="Headers",\n            info="HTTP headers for connection",\n            value={},\n            show=False,\n            advanced=True\n        ),\n        IntInput(\n            name="timeout_seconds",\n            display_name="Timeout (seconds)",\n            info="Connection timeout",\n            value=30,\n            advanced=True\n        ),\n        DropdownInput(\n            name="tool_name",\n            display_name="Tool",\n            options=[],\n            value="",\n            info="Select the MCP tool to execute",\n            show=False,\n            real_time_refresh=True\n        ),\n        DropdownInput(\n            name="output_format",\n            display_name="Output Format",\n            options=["auto", "message", "data"],\n            value="auto",\n            info="Format for the output (auto: smart detection, message: text only, data: structured)",\n            advanced=True\n        ),\n    ]\n\n    outputs = [\n        Output(display_name="Result", name="result", method="build_output"),\n    ]\n\n    async def update_tool_list(self):\n        """Update available tools from MCP server."""\n        try:\n            # Connect based on connection type\n            if self.connection_type == "http":\n                url = getattr(self, \'server_url\', \'\')\n                if not url:\n                    self.tools = []\n                    return []\n                headers = getattr(self, \'headers\', {})\n                timeout = getattr(self, \'timeout_seconds\', 30)\n                self.tools = await self.client.connect_http(url, headers, timeout)\n            elif self.connection_type == "sse":\n                url = getattr(self, \'server_url\', \'\')\n                if not url:\n                    self.tools = []\n                    return []\n                headers = getattr(self, \'headers\', {})\n                timeout = getattr(self, \'timeout_seconds\', 30)\n                self.tools = await self.client.connect_sse(url, headers, timeout)\n\n            # Cache tools for execution\n            self._tool_cache = {tool.name: tool for tool in self.tools if hasattr(tool, \'name\')}\n            return self.tools\n\n        except Exception as e:\n            logger.error(f"Failed to update tool list: {e}")\n            self.tools = []\n            self._tool_cache = {}\n            raise ValueError(f"Connection failed: {str(e)}")\n\n    def get_inputs_for_all_tools(self, tools: list) -> dict:\n        """Get input schemas for all tools - same pattern as MCPToolsComponent."""\n        inputs = {}\n        for tool in tools:\n            if not tool or not hasattr(tool, "name"):\n                continue\n            try:\n                if hasattr(tool, \'inputSchema\') and tool.inputSchema:\n                    input_schema = tool.inputSchema\n                    langflow_inputs = self.schema_to_langflow_inputs(input_schema)\n                    inputs[tool.name] = langflow_inputs\n            except (AttributeError, ValueError, TypeError, KeyError) as e:\n                logger.error(f"Error getting inputs for tool {getattr(tool, \'name\', \'unknown\')}: {e}")\n                continue\n        return inputs\n\n    def schema_to_langflow_inputs(self, input_schema: dict) -> list:\n        """Convert tool input schema to Langflow inputs."""\n        langflow_inputs = []\n\n        if not input_schema or "properties" not in input_schema:\n            return langflow_inputs\n\n        properties = input_schema["properties"]\n        required_fields = input_schema.get("required", [])\n\n        for prop_name, prop_schema in properties.items():\n            is_required = prop_name in required_fields\n            input_field = self.json_schema_to_langflow_input(prop_name, prop_schema, is_required)\n            if input_field:\n                langflow_inputs.append(input_field)\n\n        return langflow_inputs\n\n    def json_schema_to_langflow_input(self, name: str, schema: dict, required: bool = False):\n        """Convert JSON schema property to Langflow input."""\n        schema_type = schema.get("type", "string")\n        description = schema.get("description", "")\n        default = schema.get("default")\n        enum_values = schema.get("enum")\n\n        # Build common params carefully to avoid duplicates\n        common_params = {\n            "name": name,\n            "display_name": name.replace("_", " ").title(),\n            "required": required,\n            "show": True\n        }\n\n        # Only add description if it exists\n        if description:\n            common_params["info"] = description\n\n        # Only add default if it exists and is not None\n        if default is not None:\n            common_params["value"] = default\n\n        # Handle enum/choices\n        if enum_values:\n            return DropdownInput(\n                options=[str(v) for v in enum_values],\n                **common_params\n            )\n\n        # Handle different types\n        if schema_type == "string":\n            if schema.get("format") == "textarea" or len(description) > 100:\n                return MultilineInput(**common_params)\n            else:\n                return MessageTextInput(**common_params)\n        elif schema_type == "integer":\n            return IntInput(**common_params)\n        elif schema_type == "number":\n            return FloatInput(**common_params)\n        elif schema_type == "boolean":\n            return BoolInput(**common_params)\n        elif schema_type == "object":\n            return DictInput(**common_params)\n        elif schema_type == "array":\n            # For arrays, create a copy of common_params and modify info\n            array_params = common_params.copy()\n            array_info = f"{description} (JSON array format)" if description else "JSON array format"\n            array_params["info"] = array_info\n            return MessageTextInput(**array_params)\n        else:\n            return MessageTextInput(**common_params)\n\n    def remove_input_schema_from_build_config(self, build_config: dict, tool_name: str, input_schema: dict):\n        """Remove the input schema for the tool from the build config - same as MCPToolsComponent."""\n        # Keep only schemas that don\'t belong to the current tool\n        input_schema = {k: v for k, v in input_schema.items() if k != tool_name}\n        # Remove all inputs from other tools\n        for value in input_schema.values():\n            for _input in value:\n                if _input.name in build_config:\n                    build_config.pop(_input.name)\n\n    def remove_non_default_keys(self, build_config: dict) -> None:\n        """Remove non-default keys from the build config - same as MCPToolsComponent."""\n        for key in list(build_config.keys()):\n            if key not in self.default_keys:\n                build_config.pop(key)\n\n    async def update_build_config(self, build_config: dict, field_value: Any, field_name: str | None = None) -> dict:\n        """Update build configuration based on field changes - based on MCPToolsComponent pattern."""\n        try:\n            if field_name == "connection_type":\n                # Show/hide connection-specific fields\n                is_http_based = field_value in ["http", "sse"]\n                build_config["server_url"]["show"] = is_http_based\n                build_config["stdio_command"]["show"] = False  # Removed stdio support\n                build_config["stdio_args"]["show"] = False    # Removed stdio support\n                build_config["headers"]["show"] = is_http_based\n\n                # Update labels and info based on connection type\n                if field_value == "http":\n                    build_config["server_url"]["display_name"] = "HTTP Endpoint"\n                    build_config["server_url"]["info"] = "MCP HTTP endpoint (e.g., http://localhost:8000/mcp)"\n                    build_config["server_url"]["placeholder"] = "http://localhost:8000/mcp"\n                elif field_value == "sse":\n                    build_config["server_url"]["display_name"] = "SSE Server URL"\n                    build_config["server_url"]["info"] = "Server-Sent Events endpoint (e.g., http://localhost:8000/sse)"\n                    build_config["server_url"]["placeholder"] = "http://localhost:8000/sse"\n\n                # Hide tool selection until connection is made\n                build_config["tool_name"]["show"] = False\n                build_config["tool_name"]["options"] = []\n                build_config["tool_name"]["value"] = ""\n\n                # Remove any dynamic inputs\n                self.remove_non_default_keys(build_config)\n\n            elif field_name in ["server_url", "stdio_command", "stdio_args"]:\n                # Connection parameters changed, update tool list\n                if field_name == "server_url":\n                    if not field_value or not field_value.strip():\n                        # Empty URL, hide tools\n                        build_config["tool_name"]["show"] = False\n                        build_config["tool_name"]["options"] = []\n                        build_config["tool_name"]["value"] = ""\n                        self.remove_non_default_keys(build_config)\n                        return build_config\n\n                    # Basic URL validation to prevent disappearing\n                    if not (field_value.startswith(\'http://\') or field_value.startswith(\'https://\')):\n                        logger.warning(f"URL should start with http:// or https://: {field_value}")\n                        build_config["tool_name"]["show"] = False\n                        build_config["tool_name"]["options"] = ["❌ Invalid URL"]\n                        build_config["tool_name"]["value"] = "❌ Invalid URL"\n                        self.remove_non_default_keys(build_config)\n                        return build_config\n\n                if field_name == "stdio_command" and not field_value.strip():\n                    # Empty command, hide tools\n                    build_config["tool_name"]["show"] = False\n                    build_config["tool_name"]["options"] = []\n                    build_config["tool_name"]["value"] = ""\n                    self.remove_non_default_keys(build_config)\n                    return build_config\n\n                try:\n                    tools = await self.update_tool_list()\n                    tool_names = [tool.name for tool in tools if hasattr(tool, \'name\')]\n\n                    build_config["tool_name"]["options"] = tool_names\n                    build_config["tool_name"]["show"] = len(tool_names) > 0\n                    build_config["tool_name"]["value"] = tool_names[0] if tool_names else ""\n                    build_config["tool_name"]["placeholder"] = "Select a tool"\n\n                    # Remove previous dynamic inputs\n                    self.remove_non_default_keys(build_config)\n\n                    # If we have a default tool, generate its inputs\n                    if tool_names:\n                        await self._update_tool_config(build_config, tool_names[0])\n\n                except Exception as e:\n                    logger.error(f"Failed to update tool list: {e}")\n                    build_config["tool_name"]["show"] = True\n                    build_config["tool_name"]["options"] = ["❌ Connection Failed"]\n                    build_config["tool_name"]["value"] = "❌ Connection Failed"\n                    build_config["tool_name"]["placeholder"] = f"Error: {str(e)[:150]}..."\n                    self.remove_non_default_keys(build_config)\n\n            elif field_name == "tool_name" and field_value:\n                # Tool selection changed, update dynamic inputs\n                if field_value in ["❌ Connection Error", "❌ Connection Failed"]:\n                    return build_config\n\n                # Clear old inputs and update with new tool\n                await self._update_tool_config(build_config, field_value)\n\n        except Exception as e:\n            logger.error(f"Error in update_build_config: {e}")\n\n        return build_config\n\n    async def _update_tool_config(self, build_config: dict, tool_name: str) -> None:\n        """Update tool configuration - based on MCPToolsComponent pattern."""\n        if not self.tools:\n            self.tools = await self.update_tool_list()\n\n        if not tool_name:\n            return\n\n        tool_obj = next((tool for tool in self.tools if tool.name == tool_name), None)\n        if not tool_obj:\n            self.remove_non_default_keys(build_config)\n            build_config["tool_name"]["value"] = ""\n            return\n\n        try:\n            # Store current values before removing inputs\n            current_values = {}\n            for key, value in build_config.items():\n                if key not in self.default_keys and isinstance(value, dict) and "value" in value:\n                    current_values[key] = value["value"]\n\n            # Get all tool inputs and remove old ones\n            input_schema_for_all_tools = self.get_inputs_for_all_tools(self.tools)\n            self.remove_input_schema_from_build_config(build_config, tool_name, input_schema_for_all_tools)\n\n            # Get and validate new inputs\n            self.schema_inputs = self.schema_to_langflow_inputs(tool_obj.inputSchema if hasattr(tool_obj, \'inputSchema\') else {})\n            if not self.schema_inputs:\n                return\n\n            # Add new inputs to build config\n            for schema_input in self.schema_inputs:\n                if not schema_input or not hasattr(schema_input, "name"):\n                    continue\n\n                try:\n                    name = schema_input.name\n                    input_dict = schema_input.to_dict()\n\n                    # Clean up the input_dict to avoid duplicates\n                    input_dict.setdefault("value", None)\n                    input_dict.setdefault("required", True)\n\n                    # Ensure no duplicate keys that could cause conflicts\n                    if "info" not in input_dict:\n                        input_dict["info"] = ""\n\n                    build_config[name] = input_dict\n\n                    # Preserve existing value if the parameter name exists in current_values\n                    if name in current_values:\n                        build_config[name]["value"] = current_values[name]\n\n                except (AttributeError, KeyError, TypeError) as e:\n                    logger.error(f"Error processing schema input {schema_input}: {e}")\n                    continue\n                except Exception as e:\n                    logger.error(f"Unexpected error processing schema input {getattr(schema_input, \'name\', \'unknown\')}: {e}")\n                    continue\n\n        except Exception as e:\n            logger.error(f"Error updating tool config: {e}")\n            self.schema_inputs = []\n\n    async def build_output(self) -> Union[Message, Data]:\n        """Execute the selected MCP tool with provided inputs - based on MCPToolsComponent pattern."""\n        try:\n            tool_name = getattr(self, \'tool_name\', \'\')\n            if not tool_name or tool_name in ["❌ Connection Error", "❌ Connection Failed"]:\n                return Message(text="No valid tool selected")\n\n            # Get tool from cache\n            if tool_name not in self._tool_cache:\n                # Reconnect and update cache\n                await self.update_tool_list()\n\n            if tool_name not in self._tool_cache:\n                return Message(text=f"Tool \'{tool_name}\' not found")\n\n            exec_tool = self._tool_cache[tool_name]\n\n            # Collect arguments\n            tool_args = self.schema_to_langflow_inputs(exec_tool.inputSchema if hasattr(exec_tool, \'inputSchema\') else {})\n            kwargs = {}\n\n            for arg in tool_args:\n                value = getattr(self, arg.name, None)\n                if value is not None and value != "":\n                    # Handle JSON parsing for arrays/objects\n                    if isinstance(value, str) and (value.startswith(\'[\') or value.startswith(\'{\')):\n                        try:\n                            value = json.loads(value)\n                        except json.JSONDecodeError:\n                            pass  # Keep as string\n                    kwargs[arg.name] = value\n\n            # Unflatten arguments\n            unflattened_kwargs = maybe_unflatten_dict(kwargs)\n\n            # Execute tool\n            result = await self.client.call_tool(tool_name, unflattened_kwargs)\n\n            # Process result based on output format\n            output_format = getattr(self, \'output_format\', \'auto\')\n\n            if hasattr(result, \'content\') and result.content:\n                # Extract content from MCP response\n                content_items = []\n                for item in result.content:\n                    if hasattr(item, \'text\'):\n                        content_items.append(item.text)\n                    elif hasattr(item, \'model_dump\'):\n                        content_items.append(item.model_dump())\n                    else:\n                        content_items.append(str(item))\n\n                # Handle output formatting\n                if output_format == "message":\n                    if len(content_items) == 1 and isinstance(content_items[0], str):\n                        return Message(text=content_items[0])\n                    else:\n                        text_content = "\\n".join(str(item) for item in content_items)\n                        return Message(text=text_content)\n                elif output_format == "data":\n                    return Data(data={\n                        "tool_name": tool_name,\n                        "result": content_items,\n                        "arguments": unflattened_kwargs,\n                        "raw_result": str(result)\n                    })\n                else:  # auto\n                    if len(content_items) == 1 and isinstance(content_items[0], str):\n                        return Message(text=content_items[0])\n                    else:\n                        return Data(data={\n                            "tool_name": tool_name,\n                            "result": content_items,\n                            "arguments": unflattened_kwargs\n                        })\n            else:\n                # No content\n                result_str = str(result)\n                if output_format == "message":\n                    return Message(text=result_str)\n                else:\n                    return Data(data={\n                        "tool_name": tool_name,\n                        "result": result_str,\n                        "arguments": unflattened_kwargs,\n                        "raw_result": result\n                    })\n\n        except Exception as e:\n            error_msg = f"Tool execution failed: {str(e)}"\n            logger.error(error_msg)\n            return Message(text=error_msg)'
        },
        "connection_type": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": [
                "http",
                "sse",
            ],
            "options_metadata": [],
            "combobox": False,
            "dialog_inputs": {},
            "toggle": False,
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "connection_type",
            "value": "sse",
            "display_name": "Connection Type",
            "advanced": False,
            "dynamic": False,
            "info": "MCP transport type (http: Standard HTTP JSON-RPC, sse: Server-Sent Events)",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "DropdownInput",
            "load_from_db": False,
        },
        "headers": {
            "tool_mode": False,
            "trace_as_input": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "headers",
            "value": {},
            "display_name": "Headers",
            "advanced": True,
            "dynamic": False,
            "info": "HTTP headers for connection",
            "title_case": False,
            "type": "dict",
            "_input_type": "DictInput",
        },
        "output_format": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": [
                "auto",
                "message",
                "data",
            ],
            "options_metadata": [],
            "combobox": False,
            "dialog_inputs": {},
            "toggle": False,
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "output_format",
            "value": "auto",
            "display_name": "Output Format",
            "advanced": True,
            "dynamic": False,
            "info": "Format for the output (auto: smart detection, message: text only, data: structured)",
            "title_case": False,
            "type": "str",
            "_input_type": "DropdownInput",
        },
        "server_url": {
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "http://localhost:8000/sse",
            "show": True,
            "name": "server_url",
            "value": "",
            "display_name": "SSE Server URL",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "Server-Sent Events endpoint (e.g., http://localhost:8000/sse)",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "MessageTextInput",
        },
        "stdio_args": {
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "server.py",
            "show": False,
            "name": "stdio_args",
            "value": "",
            "display_name": "Arguments",
            "advanced": True,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "Command arguments separated by spaces",
            "title_case": False,
            "type": "str",
            "_input_type": "MessageTextInput",
        },
        "stdio_command": {
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "python",
            "show": False,
            "name": "stdio_command",
            "value": "{   \"mcpServers\": {     \"context7-mcp\": {       \"command\": \"npx\",       \"args\": [         \"-y\",         \"@smithery/cli@latest\",         \"run\",         \"@upstash/context7-mcp\",         \"--key\",         \"f9899c50-7793-4ef9-b554-66eec508970f\"       ]     }   } }",
            "display_name": "Command",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "Command to run for stdio connection (e.g., 'python', 'node')",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "MessageTextInput",
        },
        "timeout_seconds": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "timeout_seconds",
            "value": 30,
            "display_name": "Timeout (seconds)",
            "advanced": True,
            "dynamic": False,
            "info": "Connection timeout",
            "title_case": False,
            "type": "int",
            "_input_type": "IntInput",
        },
        "tool_name": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": [],
            "options_metadata": [],
            "combobox": False,
            "dialog_inputs": {},
            "toggle": False,
            "required": False,
            "placeholder": "Select a tool",
            "show": False,
            "name": "tool_name",
            "value": "",
            "display_name": "Tool",
            "advanced": False,
            "dynamic": False,
            "info": "Select the MCP tool to execute",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "DropdownInput",
        },
    },
}