QPIAI_MCP_NODE_TEMPLATE = {
    "display_name": "QpiAI MCP Node",
    "description": "Connect to QpiAI hosted MCP servers and use their tools directly as workflow nodes",
    "icon": "QpiAI",
    "base_classes": [
        "Data",
        "Message",
    ],
    "field_order": [
        "_type",
        "code",
        "output_format",
        "selected_tool",
        "tool_api_credentials",
        "tool_api_url",
        "tool_name",
    ],
    "outputs": [
        {
            "types": [
                "Data",
                "Message",
            ],
            "selected": "Data",
            "name": "result",
            "hidden": None,
            "display_name": "Result",
            "method": "build_output",
            "value": "__UNDEFINED__",
            "cache": True,
            "required_inputs": None,
            "allows_loop": False,
            "group_outputs": False,
            "options": None,
            "tool_mode": True,
        },
    ],
    "template": {
        "_type": "Component",
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": 'import json\nimport re\nfrom typing import Any, Dict, List, Optional, Union\nimport asyncio\nfrom contextlib import AsyncExitStack\n\nimport httpx\nfrom mcp import ClientSession, types\nfrom mcp.client.sse import sse_client\n\nfrom langflow.custom.custom_component.component import Component\nfrom langflow.io import (\n    BoolInput,\n    DropdownInput,\n    IntInput,\n    MessageTextInput,\n    MultilineInput,\n    Output,\n    StrInput,\n    DictInput,\n    FloatInput\n)\nfrom langflow.logging import logger\nfrom langflow.schema.data import Data\nfrom langflow.schema.message import Message\n\n\ndef maybe_unflatten_dict(flat: Dict[str, Any]) -> Dict[str, Any]:\n    """Convert flat dictionary with dot notation keys to nested structure."""\n    if not any(re.search(r"\\.|\\\\[\\\\d+\\\\]", key) for key in flat):\n        return flat\n\n    nested: Dict[str, Any] = {}\n    array_re = re.compile(r"^(.+)\\\\[(\\\\d+)\\\\]$")\n\n    for key, val in flat.items():\n        parts = key.split(".")\n        cur = nested\n        for i, part in enumerate(parts):\n            m = array_re.match(part)\n            if m:\n                name, idx = m.group(1), int(m.group(2))\n                lst = cur.setdefault(name, [])\n                while len(lst) <= idx:\n                    lst.append({})\n                if i == len(parts) - 1:\n                    lst[idx] = val\n                else:\n                    cur = lst[idx]\n            elif i == len(parts) - 1:\n                cur[part] = val\n            else:\n                cur = cur.setdefault(part, {})\n\n    return nested\n\n\nclass SSEOptimizedMCPClient:\n    """MCP client optimized for SSE connection issues"""\n\n    def __init__(self):\n        # Connection state\n        self.session: Optional[ClientSession] = None\n        self.sse = None\n        self.write = None\n        self.exit_stack = AsyncExitStack()\n\n        # Connection management\n        self._connection_lock = asyncio.Lock()\n\n        # Timeouts based on diagnostic results\n        self.basic_timeout = 7      # Basic connectivity (5s + 2s safety)\n        self.sse_timeout = 25       # SSE streaming needs more time\n        self.operation_timeout = 10 # Individual operations\n        self.retry_delay = 2        # Delay between retries\n\n    async def _wait_for_server_ready(self, url: str) -> bool:\n        """Wait for server to be ready before attempting SSE"""\n        logger.debug("Checking if server is ready for SSE connection")\n\n        max_attempts = 3\n        for attempt in range(max_attempts):\n            try:\n                async with httpx.AsyncClient(timeout=self.basic_timeout) as client:\n                    response = await client.head(url)\n                    if response.status_code == 200:\n                        logger.debug(f"Server ready on attempt {attempt + 1}")\n                        return True\n            except Exception as e:\n                logger.debug(f"Server readiness check {attempt + 1} failed: {e}")\n                if attempt < max_attempts - 1:\n                    await asyncio.sleep(1)  # Brief wait between checks\n\n        return False\n\n    async def _create_sse_connection_with_retries(self, url: str, headers: Optional[dict[str, str]] = None) -> list[types.Tool]:\n        """Create SSE connection with specific retry strategy for SSE issues"""\n        if headers is None:\n            headers = {}\n\n        logger.info(f"Creating SSE connection with retries to: {url}")\n        await self._cleanup_connection()\n\n        # Wait for server to be ready first\n        if not await self._wait_for_server_ready(url):\n            raise ValueError("Server not responding to readiness checks")\n\n        # Try SSE connection with progressive timeouts\n        sse_timeouts = [15, 25, 35]  # Progressive SSE timeouts\n\n        for attempt, sse_timeout in enumerate(sse_timeouts):\n            try:\n                logger.info(f"SSE attempt {attempt + 1}/{len(sse_timeouts)} with {sse_timeout}s timeout")\n\n                async with asyncio.timeout(sse_timeout + 5):  # Add buffer to asyncio timeout\n                    # Create SSE client with current timeout\n                    sse_transport = await self.exit_stack.enter_async_context(\n                        sse_client(url, headers, self.basic_timeout, sse_timeout)\n                    )\n                    self.sse, self.write = sse_transport\n                    logger.debug(f"SSE transport created with {sse_timeout}s timeout")\n\n                    # Create and initialize session quickly\n                    async with asyncio.timeout(self.operation_timeout):\n                        self.session = await self.exit_stack.enter_async_context(\n                            ClientSession(self.sse, self.write)\n                        )\n                        await self.session.initialize()\n                        logger.debug("Session initialized successfully")\n\n                    # Get tools quickly\n                    async with asyncio.timeout(self.operation_timeout):\n                        response = await self.session.list_tools()\n                        logger.info(f"Successfully connected with {sse_timeout}s timeout, found {len(response.tools)} tools")\n                        return response.tools\n\n            except asyncio.TimeoutError:\n                logger.warning(f"SSE attempt {attempt + 1} timed out after {sse_timeout}s")\n                await self._cleanup_connection()\n                if attempt < len(sse_timeouts) - 1:\n                    logger.info(f"Waiting {self.retry_delay}s before next attempt")\n                    await asyncio.sleep(self.retry_delay)\n                continue\n\n            except Exception as e:\n                logger.warning(f"SSE attempt {attempt + 1} failed: {str(e)}")\n                await self._cleanup_connection()\n                if attempt < len(sse_timeouts) - 1:\n                    # For non-timeout errors, wait a bit longer\n                    wait_time = self.retry_delay * (attempt + 1)\n                    logger.info(f"Waiting {wait_time}s before next attempt")\n                    await asyncio.sleep(wait_time)\n                continue\n\n        # All attempts failed\n        raise ValueError("All SSE connection attempts failed - server may be overloaded")\n\n    async def _cleanup_connection(self):\n        """Clean up connection resources"""\n        try:\n            if self.exit_stack:\n                await asyncio.wait_for(self.exit_stack.aclose(), timeout=5)\n        except Exception as e:\n            logger.debug(f"Cleanup error (ignored): {e}")\n        finally:\n            self.session = None\n            self.sse = None\n            self.write = None\n            self.exit_stack = AsyncExitStack()\n\n    async def _is_session_healthy(self) -> bool:\n        """Quick health check"""\n        if not self.session:\n            return False\n        try:\n            async with asyncio.timeout(5):\n                await self.session.list_tools()\n                return True\n        except Exception:\n            return False\n\n    async def get_tools_optimized(self, url: str, headers: Optional[dict[str, str]] = None) -> list[types.Tool]:\n        """Get tools with SSE optimization"""\n        async with self._connection_lock:\n            try:\n                # Check if existing session is healthy\n                if self.session and await self._is_session_healthy():\n                    logger.debug("Using existing healthy session")\n                    async with asyncio.timeout(self.operation_timeout):\n                        response = await self.session.list_tools()\n                        return response.tools\n\n                # Need new connection\n                logger.info("Creating new SSE-optimized connection")\n                return await self._create_sse_connection_with_retries(url, headers)\n\n            except Exception as e:\n                await self._cleanup_connection()\n                raise ValueError(f"Optimized connection failed: {str(e)}")\n\n    async def close(self):\n        """Close connection"""\n        async with self._connection_lock:\n            await self._cleanup_connection()\n\n    async def call_tool(self, tool_name: str, arguments: Dict[str, Any]) -> Any:\n        """Call a specific tool with arguments."""\n        if not self.session:\n            raise ValueError("Session not initialized. Call get_tools_optimized first.")\n\n        try:\n            result = await self.session.call_tool(tool_name, arguments=arguments)\n            return result\n        except Exception as e:\n            logger.error(f"Tool \'{tool_name}\' execution failed: {e}")\n            raise\n\n\nclass QpiAIMCPNode(Component):\n    """QpiAI MCP Node Component - Use QpiAI MCP server tools directly as nodes without agents."""\n\n    display_name = "QpiAI MCP Node"\n    description = "Connect to QpiAI hosted MCP servers and use their tools directly as workflow nodes"\n    icon = "QpiAI"\n    name = "QpiAIMCPNode"\n\n    # Use same pattern as MCPNodeComponent\n    schema_inputs: list = []\n    client = SSEOptimizedMCPClient()\n    tools: list = []\n    _tool_cache: dict = {}\n    default_keys: list[str] = [\n        "code",\n        "_type",\n        "tool_api_url",\n        "tool_api_credentials",\n        "tool_name",\n        "selected_tool",\n        "output_format"\n    ]\n\n    inputs = [\n        MessageTextInput(\n            name="tool_api_url",\n            display_name="Tool API URL",\n            info="QpiAI tool API base URL",\n            value="",\n            tool_mode=False,\n            real_time_refresh=True,\n        ),\n        MessageTextInput(\n            name="tool_api_credentials",\n            display_name="Tool API Credentials",\n            info="QpiAI API credentials",\n            value="",\n            tool_mode=False,\n            real_time_refresh=True,\n        ),\n        MessageTextInput(\n            name="tool_name",\n            display_name="Service Name",\n            info="QpiAI service name (e.g., gmail, slack)",\n            value="gmail",\n            tool_mode=False,\n            real_time_refresh=True,\n        ),\n        DropdownInput(\n            name="selected_tool",\n            display_name="Tool",\n            options=[],\n            value="",\n            info="Select the specific tool to execute",\n            show=False,\n            real_time_refresh=True\n        ),\n        DropdownInput(\n            name="output_format",\n            display_name="Output Format",\n            options=["auto", "message", "data"],\n            value="auto",\n            info="Format for the output (auto: smart detection, message: text only, data: structured)",\n            advanced=True\n        ),\n    ]\n\n    outputs = [\n        Output(display_name="Result", name="result", method="build_output"),\n    ]\n\n    async def update_tool_list(self):\n        """Update available tools from QpiAI MCP server."""\n        try:\n            tool_api_url = getattr(self, \'tool_api_url\', \'\')\n            tool_name = getattr(self, \'tool_name\', \'\')\n            tool_api_credentials = getattr(self, \'tool_api_credentials\', \'\')\n\n            if not tool_api_url or not tool_name or not tool_api_credentials:\n                self.tools = []\n                return []\n\n            url = f"{tool_api_url}/{tool_name}/{tool_api_credentials}"\n            self.tools = await self.client.get_tools_optimized(url)\n\n            # Cache tools for execution\n            self._tool_cache = {tool.name: tool for tool in self.tools if hasattr(tool, \'name\')}\n            return self.tools\n\n        except Exception as e:\n            logger.error(f"Failed to update tool list: {e}")\n            self.tools = []\n            self._tool_cache = {}\n            raise ValueError(f"Connection failed: {str(e)}")\n\n    def get_inputs_for_all_tools(self, tools: list) -> dict:\n        """Get input schemas for all tools - same pattern as MCPNodeComponent."""\n        inputs = {}\n        for tool in tools:\n            if not tool or not hasattr(tool, "name"):\n                continue\n            try:\n                if hasattr(tool, \'inputSchema\') and tool.inputSchema:\n                    input_schema = tool.inputSchema\n                    langflow_inputs = self.schema_to_langflow_inputs(input_schema)\n                    inputs[tool.name] = langflow_inputs\n            except (AttributeError, ValueError, TypeError, KeyError) as e:\n                logger.error(f"Error getting inputs for tool {getattr(tool, \'name\', \'unknown\')}: {e}")\n                continue\n        return inputs\n\n    def schema_to_langflow_inputs(self, input_schema: dict) -> list:\n        """Convert tool input schema to Langflow inputs."""\n        langflow_inputs = []\n\n        if not input_schema or "properties" not in input_schema:\n            return langflow_inputs\n\n        properties = input_schema["properties"]\n        required_fields = input_schema.get("required", [])\n\n        for prop_name, prop_schema in properties.items():\n            is_required = prop_name in required_fields\n            input_field = self.json_schema_to_langflow_input(prop_name, prop_schema, is_required)\n            if input_field:\n                langflow_inputs.append(input_field)\n\n        return langflow_inputs\n\n    def json_schema_to_langflow_input(self, name: str, schema: dict, required: bool = False):\n        """Convert JSON schema property to Langflow input."""\n        schema_type = schema.get("type", "string")\n        description = schema.get("description", "")\n        default = schema.get("default")\n        enum_values = schema.get("enum")\n\n        # Build common params carefully to avoid duplicates\n        common_params = {\n            "name": name,\n            "display_name": name.replace("_", " ").title(),\n            "required": required,\n            "show": True\n        }\n\n        # Only add description if it exists\n        if description:\n            common_params["info"] = description\n\n        # Only add default if it exists and is not None\n        if default is not None:\n            common_params["value"] = default\n\n        # Handle enum/choices\n        if enum_values:\n            return DropdownInput(\n                options=[str(v) for v in enum_values],\n                **common_params\n            )\n\n        # Handle different types\n        if schema_type == "string":\n            if schema.get("format") == "textarea" or len(description) > 100:\n                return MultilineInput(**common_params)\n            else:\n                return MessageTextInput(**common_params)\n        elif schema_type == "integer":\n            return IntInput(**common_params)\n        elif schema_type == "number":\n            return FloatInput(**common_params)\n        elif schema_type == "boolean":\n            return BoolInput(**common_params)\n        elif schema_type == "object":\n            return DictInput(**common_params)\n        elif schema_type == "array":\n            # For arrays, create a copy of common_params and modify info\n            array_params = common_params.copy()\n            array_info = f"{description} (JSON array format)" if description else "JSON array format"\n            array_params["info"] = array_info\n            return MessageTextInput(**array_params)\n        else:\n            return MessageTextInput(**common_params)\n\n    def remove_input_schema_from_build_config(self, build_config: dict, tool_name: str, input_schema: dict):\n        """Remove the input schema for the tool from the build config - same as MCPNodeComponent."""\n        # Keep only schemas that don\'t belong to the current tool\n        input_schema = {k: v for k, v in input_schema.items() if k != tool_name}\n        # Remove all inputs from other tools\n        for value in input_schema.values():\n            for _input in value:\n                if _input.name in build_config:\n                    build_config.pop(_input.name)\n\n    def remove_non_default_keys(self, build_config: dict) -> None:\n        """Remove non-default keys from the build config - same as MCPNodeComponent."""\n        for key in list(build_config.keys()):\n            if key not in self.default_keys:\n                build_config.pop(key)\n\n    async def update_build_config(self, build_config: dict, field_value: Any, field_name: str | None = None) -> dict:\n        """Update build configuration based on field changes - based on MCPNodeComponent pattern."""\n        try:\n            if field_name in ["tool_api_url", "tool_api_credentials", "tool_name"]:\n                # Connection parameters changed, update tool list\n                tool_api_url = getattr(self, \'tool_api_url\', \'\') if field_name != \'tool_api_url\' else field_value\n                tool_name = getattr(self, \'tool_name\', \'\') if field_name != \'tool_name\' else field_value\n                tool_api_credentials = getattr(self, \'tool_api_credentials\', \'\') if field_name != \'tool_api_credentials\' else field_value\n\n                if not tool_api_url or not tool_name or not tool_api_credentials:\n                    # Missing required fields, hide tools\n                    build_config["selected_tool"]["show"] = False\n                    build_config["selected_tool"]["options"] = []\n                    build_config["selected_tool"]["value"] = ""\n                    self.remove_non_default_keys(build_config)\n                    return build_config\n\n                # Set the current values to ensure update_tool_list has them\n                if field_name == \'tool_api_url\':\n                    self.tool_api_url = field_value\n                elif field_name == \'tool_name\':\n                    self.tool_name = field_value\n                elif field_name == \'tool_api_credentials\':\n                    self.tool_api_credentials = field_value\n\n                try:\n                    tools = await self.update_tool_list()\n                    tool_names = [tool.name for tool in tools if hasattr(tool, \'name\')]\n\n                    build_config["selected_tool"]["options"] = tool_names\n                    build_config["selected_tool"]["show"] = len(tool_names) > 0\n                    build_config["selected_tool"]["value"] = tool_names[0] if tool_names else ""\n                    build_config["selected_tool"]["placeholder"] = "Select a tool"\n\n                    # Remove previous dynamic inputs\n                    self.remove_non_default_keys(build_config)\n\n                    # If we have a default tool, generate its inputs\n                    if tool_names:\n                        await self._update_tool_config(build_config, tool_names[0])\n\n                except Exception as e:\n                    logger.error(f"Failed to update tool list: {e}")\n                    build_config["selected_tool"]["show"] = True\n                    build_config["selected_tool"]["options"] = ["❌ Connection Failed"]\n                    build_config["selected_tool"]["value"] = "❌ Connection Failed"\n                    build_config["selected_tool"]["placeholder"] = f"Error: {str(e)[:150]}..."\n                    self.remove_non_default_keys(build_config)\n\n            elif field_name == "selected_tool" and field_value:\n                # Tool selection changed, update dynamic inputs\n                if field_value in ["❌ Connection Error", "❌ Connection Failed"]:\n                    return build_config\n\n                # Clear old inputs and update with new tool\n                await self._update_tool_config(build_config, field_value)\n\n        except Exception as e:\n            logger.error(f"Error in update_build_config: {e}")\n\n        return build_config\n\n    async def _update_tool_config(self, build_config: dict, tool_name: str) -> None:\n        """Update tool configuration - based on MCPNodeComponent pattern."""\n        if not self.tools:\n            self.tools = await self.update_tool_list()\n\n        if not tool_name:\n            return\n\n        tool_obj = next((tool for tool in self.tools if tool.name == tool_name), None)\n        if not tool_obj:\n            self.remove_non_default_keys(build_config)\n            build_config["selected_tool"]["value"] = ""\n            return\n\n        try:\n            # Store current values before removing inputs\n            current_values = {}\n            for key, value in build_config.items():\n                if key not in self.default_keys and isinstance(value, dict) and "value" in value:\n                    current_values[key] = value["value"]\n\n            # Get all tool inputs and remove old ones\n            input_schema_for_all_tools = self.get_inputs_for_all_tools(self.tools)\n            self.remove_input_schema_from_build_config(build_config, tool_name, input_schema_for_all_tools)\n\n            # Get and validate new inputs\n            self.schema_inputs = self.schema_to_langflow_inputs(tool_obj.inputSchema if hasattr(tool_obj, \'inputSchema\') else {})\n            if not self.schema_inputs:\n                return\n\n            # Add new inputs to build config\n            for schema_input in self.schema_inputs:\n                if not schema_input or not hasattr(schema_input, "name"):\n                    continue\n\n                try:\n                    name = schema_input.name\n                    input_dict = schema_input.to_dict()\n\n                    # Clean up the input_dict to avoid duplicates\n                    input_dict.setdefault("value", None)\n                    input_dict.setdefault("required", True)\n\n                    # Ensure no duplicate keys that could cause conflicts\n                    if "info" not in input_dict:\n                        input_dict["info"] = ""\n\n                    build_config[name] = input_dict\n\n                    # Preserve existing value if the parameter name exists in current_values\n                    if name in current_values:\n                        build_config[name]["value"] = current_values[name]\n\n                except (AttributeError, KeyError, TypeError) as e:\n                    logger.error(f"Error processing schema input {schema_input}: {e}")\n                    continue\n                except Exception as e:\n                    logger.error(f"Unexpected error processing schema input {getattr(schema_input, \'name\', \'unknown\')}: {e}")\n                    continue\n\n        except Exception as e:\n            logger.error(f"Error updating tool config: {e}")\n            self.schema_inputs = []\n\n    async def build_output(self) -> Union[Message, Data]:\n        """Execute the selected QpiAI MCP tool with provided inputs - based on MCPNodeComponent pattern."""\n        try:\n            selected_tool = getattr(self, \'selected_tool\', \'\')\n            if not selected_tool or selected_tool in ["❌ Connection Error", "❌ Connection Failed"]:\n                return Message(text="No valid tool selected")\n\n            # Get tool from cache\n            if selected_tool not in self._tool_cache:\n                # Reconnect and update cache\n                await self.update_tool_list()\n\n            if selected_tool not in self._tool_cache:\n                return Message(text=f"Tool \'{selected_tool}\' not found")\n\n            exec_tool = self._tool_cache[selected_tool]\n\n            # Collect arguments\n            tool_args = self.schema_to_langflow_inputs(exec_tool.inputSchema if hasattr(exec_tool, \'inputSchema\') else {})\n            kwargs = {}\n\n            for arg in tool_args:\n                value = getattr(self, arg.name, None)\n                if value is not None and value != "":\n                    # Handle JSON parsing for arrays/objects\n                    if isinstance(value, str) and (value.startswith(\'[\') or value.startswith(\'{\')):\n                        try:\n                            value = json.loads(value)\n                        except json.JSONDecodeError:\n                            pass  # Keep as string\n                    kwargs[arg.name] = value\n\n            # Unflatten arguments\n            unflattened_kwargs = maybe_unflatten_dict(kwargs)\n\n            # Execute tool\n            result = await self.client.call_tool(selected_tool, unflattened_kwargs)\n\n            # Process result based on output format\n            output_format = getattr(self, \'output_format\', \'auto\')\n\n            if hasattr(result, \'content\') and result.content:\n                # Extract content from MCP response\n                content_items = []\n                for item in result.content:\n                    if hasattr(item, \'text\'):\n                        content_items.append(item.text)\n                    elif hasattr(item, \'model_dump\'):\n                        content_items.append(item.model_dump())\n                    else:\n                        content_items.append(str(item))\n\n                # Handle output formatting\n                if output_format == "message":\n                    if len(content_items) == 1 and isinstance(content_items[0], str):\n                        return Message(text=content_items[0])\n                    else:\n                        text_content = "\\\\n".join(str(item) for item in content_items)\n                        return Message(text=text_content)\n                elif output_format == "data":\n                    return Data(data={\n                        "tool_name": selected_tool,\n                        "result": content_items,\n                        "arguments": unflattened_kwargs,\n                        "raw_result": str(result)\n                    })\n                else:  # auto\n                    if len(content_items) == 1 and isinstance(content_items[0], str):\n                        return Message(text=content_items[0])\n                    else:\n                        return Data(data={\n                            "tool_name": selected_tool,\n                            "result": content_items,\n                            "arguments": unflattened_kwargs\n                        })\n            else:\n                # No content\n                result_str = str(result)\n                if output_format == "message":\n                    return Message(text=result_str)\n                else:\n                    return Data(data={\n                        "tool_name": selected_tool,\n                        "result": result_str,\n                        "arguments": unflattened_kwargs,\n                        "raw_result": result\n                    })\n\n        except Exception as e:\n            error_msg = f"Tool execution failed: {str(e)}"\n            logger.error(error_msg)\n            return Message(text=error_msg)\n\n    async def cleanup(self):\n        """Cleanup for Langflow"""\n        try:\n            await self.client.close()\n        except Exception as e:\n            logger.debug(f"Cleanup error: {e}")'
        },
        "output_format": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": [
                "auto",
                "message",
                "data",
            ],
            "options_metadata": [],
            "combobox": False,
            "dialog_inputs": {},
            "toggle": False,
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "output_format",
            "value": "auto",
            "display_name": "Output Format",
            "advanced": True,
            "dynamic": False,
            "info": "Format for the output (auto: smart detection, message: text only, data: structured)",
            "title_case": False,
            "type": "str",
            "_input_type": "DropdownInput",
        },
        "selected_tool": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": [],
            "options_metadata": [],
            "combobox": False,
            "dialog_inputs": {},
            "toggle": False,
            "required": False,
            "placeholder": "",
            "show": False,
            "name": "selected_tool",
            "value": "read_emails",
            "display_name": "Tool",
            "advanced": False,
            "dynamic": False,
            "info": "Select the specific tool to execute",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "DropdownInput",
            "load_from_db": False,
        },
        "tool_api_credentials": {
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "load_from_db": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "tool_api_credentials",
            "value": "TOOL_API_CREDENTIALS",
            "display_name": "Tool API Credentials",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "QpiAI API credentials",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "MessageTextInput",
        },
        "tool_api_url": {
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "load_from_db": True,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "tool_api_url",
            "value": "TOOL_API_URL",
            "display_name": "Tool API URL",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "QpiAI tool API base URL",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "MessageTextInput",
        },
        "tool_name": {
            "tool_mode": False,
            "trace_as_input": True,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "tool_name",
            "value": "gmail",
            "display_name": "Service Name",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "QpiAI service name (e.g., gmail, slack)",
            "real_time_refresh": True,
            "title_case": False,
            "type": "str",
            "_input_type": "MessageTextInput",
        },
    },
}