# component_templates.py - Complete file with TextInput and TextOutput templates
TEXT_INPUT_TEMPLATE = {
    "display_name": "Text Input",
    "description": "Get user text inputs.",
    "icon": "type",
    "base_classes": ["Message"],
    "field_order": [
        "_type",
        "code",
        "input_value",
    ],
    "outputs": [
        {
            "types": ["Message"],
            "selected": "Message",
            "name": "text",
            "display_name": "Output Text",
            "method": "text_response",
            "value": "__UNDEFINED__",
            "cache": True,
            "required_inputs": None,
            "allows_loop": False,
            "group_outputs": False,
            "options": None,
            "tool_mode": True,
        },
    ],
    "template": {
        "_type": "Component",
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": 'from langflow.base.io.text import TextComponent\nfrom langflow.io import MultilineInput, Output\nfrom langflow.schema.message import Message\n\n\nclass TextInputComponent(TextComponent):\n    display_name = "Text Input"\n    description = "Get user text inputs."\n    icon = "type"\n    name = "TextInput"\n\n    inputs = [\n        MultilineInput(\n            name="input_value",\n            display_name="Text",\n            info="Text to be passed as input.",\n        ),\n    ]\n    outputs = [\n        Output(display_name="Output Text", name="text", method="text_response"),\n    ]\n\n    def text_response(self) -> Message:\n        return Message(\n            text=self.input_value,\n        )\n'
        },
        "input_value": {
            "tool_mode": False,
            "trace_as_input": True,
            "multiline": True,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "input_value",
            "value": "",
            "display_name": "Text",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "Text to be passed as input.",
            "title_case": False,
            "copy_field": False,
            "type": "str",
            "_input_type": "MultilineInput",
        },
    },
}

TEXT_OUTPUT_TEMPLATE = {
    "display_name": "Text Output",
    "description": "Sends text output via API.",
    "icon": "type",
    "base_classes": ["Message"],
    "field_order": [
        "_type",
        "code",
        "input_value",
    ],
    "outputs": [
        {
            "types": ["Message"],
            "selected": "Message",
            "name": "text",
            "hidden": None,
            "display_name": "Output Text",
            "method": "text_response",
            "value": "__UNDEFINED__",
            "cache": True,
            "required_inputs": None,
            "allows_loop": False,
            "group_outputs": False,
            "options": None,
            "tool_mode": True,
        },
    ],
    "template": {
        "_type": "Component",
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": 'from langflow.base.io.text import TextComponent\nfrom langflow.io import MultilineInput, Output\nfrom langflow.schema.message import Message\n\n\nclass TextOutputComponent(TextComponent):\n    display_name = "Text Output"\n    description = "Sends text output via API."\n    icon = "type"\n    name = "TextOutput"\n\n    inputs = [\n        MultilineInput(\n            name="input_value",\n            display_name="Inputs",\n            info="Text to be passed as output.",\n        ),\n    ]\n    outputs = [\n        Output(display_name="Output Text", name="text", method="text_response"),\n    ]\n\n    def text_response(self) -> Message:\n        message = Message(\n            text=self.input_value,\n        )\n        self.status = self.input_value\n        return message\n'
        },
        "input_value": {
            "tool_mode": False,
            "trace_as_input": True,
            "multiline": True,
            "trace_as_metadata": True,
            "load_from_db": False,
            "list": False,
            "list_add_label": "Add More",
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "input_value",
            "value": "",
            "display_name": "Inputs",
            "advanced": False,
            "input_types": ["Message"],
            "dynamic": False,
            "info": "Text to be passed as output.",
            "title_case": False,
            "copy_field": False,
            "type": "str",
            "_input_type": "MultilineInput",
        },
    },
}