TYPE_CONVERT_TEMPLATE = {
    "display_name": "Type Convert",
    "description": "Convert between different types (Message, Data, DataFrame)",
    "icon": "repeat",
    "base_classes": ["Message"],
    "field_order": [
        "_type",
        "input_data",
        "code",
        "output_type",
    ],
    "outputs": [
        {
            "types": ["Message"],
            "selected": "Message",
            "name": "message_output",
            "display_name": "Message Output",
            "method": "convert_to_message",
            "value": "__UNDEFINED__",
            "cache": True,
            "allows_loop": False,
            "group_outputs": False,
            "tool_mode": True,
        },
    ],
    "template": {
        "_type": "Component",
        "input_data": {
            "trace_as_metadata": True,
            "list": False,
            "list_add_label": "Add More",
            "required": True,
            "placeholder": "",
            "show": True,
            "name": "input_data",
            "value": "",
            "display_name": "Input",
            "advanced": False,
            "input_types": [
                "Message",
                "Data",
                "DataFrame",
            ],
            "dynamic": False,
            "info": "Accept Message, Data or DataFrame as input",
            "title_case": False,
            "type": "other",
            "_input_type": "HandleInput",
        },
        "code": {
            "advanced": True,
            "dynamic": True,
            "fileTypes": [],
            "file_path": "",
            "info": "",
            "list": False,
            "load_from_db": False,
            "multiline": True,
            "name": "code",
            "password": False,
            "placeholder": "",
            "required": True,
            "show": True,
            "title_case": False,
            "type": "code",
            "value": 'from typing import Any\n\nfrom langflow.custom import Component\nfrom langflow.io import HandleInput, Output, TabInput\nfrom langflow.schema import Data, DataFrame, Message\n\n\ndef convert_to_message(v) -> Message:\n    """Convert input to Message type.\n\n    Args:\n        v: Input to convert (Message, Data, DataFrame, or dict)\n\n    Returns:\n        Message: Converted Message object\n    """\n    return v if isinstance(v, Message) else v.to_message()\n\n\ndef convert_to_data(v: DataFrame | Data | Message | dict) -> Data:\n    """Convert input to Data type.\n\n    Args:\n        v: Input to convert (Message, Data, DataFrame, or dict)\n\n    Returns:\n        Data: Converted Data object\n    """\n    if isinstance(v, dict):\n        return Data(v)\n    return v if isinstance(v, Data) else v.to_data()\n\n\ndef convert_to_dataframe(v: DataFrame | Data | Message | dict) -> DataFrame:\n    """Convert input to DataFrame type.\n\n    Args:\n        v: Input to convert (Message, Data, DataFrame, or dict)\n\n    Returns:\n        DataFrame: Converted DataFrame object\n    """\n    if isinstance(v, dict):\n        return DataFrame([v])\n    return v if isinstance(v, DataFrame) else v.to_dataframe()\n\n\nclass TypeConverterComponent(Component):\n    display_name = "Type Convert"\n    description = "Convert between different types (Message, Data, DataFrame)"\n    icon = "repeat"\n\n    inputs = [\n        HandleInput(\n            name="input_data",\n            display_name="Input",\n            input_types=["Message", "Data", "DataFrame"],\n            info="Accept Message, Data or DataFrame as input",\n            required=True,\n        ),\n        TabInput(\n            name="output_type",\n            display_name="Output Type",\n            options=["Message", "Data", "DataFrame"],\n            info="Select the desired output data type",\n            real_time_refresh=True,\n            value="Message",\n        ),\n    ]\n\n    outputs = [\n        Output(\n            display_name="Message Output",\n            name="message_output",\n            method="convert_to_message",\n        )\n    ]\n\n    def update_outputs(self, frontend_node: dict, field_name: str, field_value: Any) -> dict:\n        """Dynamically show only the relevant output based on the selected output type."""\n        if field_name == "output_type":\n            # Start with empty outputs\n            frontend_node["outputs"] = []\n\n            # Add only the selected output type\n            if field_value == "Message":\n                frontend_node["outputs"].append(\n                    Output(\n                        display_name="Message Output",\n                        name="message_output",\n                        method="convert_to_message",\n                    ).to_dict()\n                )\n            elif field_value == "Data":\n                frontend_node["outputs"].append(\n                    Output(\n                        display_name="Data Output",\n                        name="data_output",\n                        method="convert_to_data",\n                    ).to_dict()\n                )\n            elif field_value == "DataFrame":\n                frontend_node["outputs"].append(\n                    Output(\n                        display_name="DataFrame Output",\n                        name="dataframe_output",\n                        method="convert_to_dataframe",\n                    ).to_dict()\n                )\n\n        return frontend_node\n\n    def convert_to_message(self) -> Message:\n        """Convert input to Message type."""\n        input_value = self.input_data[0] if isinstance(self.input_data, list) else self.input_data\n\n        # Handle string input by converting to Message first\n        if isinstance(input_value, str):\n            input_value = Message(text=input_value)\n\n        return convert_to_message(input_value)\n\n    def convert_to_data(self) -> Data:\n        """Convert input to Data type."""\n        input_value = self.input_data[0] if isinstance(self.input_data, list) else self.input_data\n\n        # Handle string input by converting to Message first\n        if isinstance(input_value, str):\n            input_value = Message(text=input_value)\n\n        return convert_to_data(input_value)\n\n    def convert_to_dataframe(self) -> DataFrame:\n        """Convert input to DataFrame type."""\n        input_value = self.input_data[0] if isinstance(self.input_data, list) else self.input_data\n\n        # Handle string input by converting to Message first\n        if isinstance(input_value, str):\n            input_value = Message(text=input_value)\n\n        return convert_to_dataframe(input_value)\n'
        },
        "output_type": {
            "tool_mode": False,
            "trace_as_metadata": True,
            "options": [
                "Message",
                "Data",
                "DataFrame",
            ],
            "required": False,
            "placeholder": "",
            "show": True,
            "name": "output_type",
            "value": "Message",
            "display_name": "Output Type",
            "advanced": False,
            "dynamic": False,
            "info": "Select the desired output data type",
            "real_time_refresh": True,
            "title_case": False,
            "type": "tab",
            "_input_type": "TabInput",
        },
    },
}